### ISSUE TITLE
Provide a way to pass in flags to the development build

### ISSUE THREAD

**Issue by jbachhardie** [stripe/stripe-apps#154]
**Is your feature request related to a problem? Please describe.**
We've found the need to run the same app in different configurations during development. For example, to run it against a mock backend vs a locally-running backend vs the production backend. However, the Stripe CLI doesn't seem to provide a way to pass in any flags or environment variables that could be read in the code.

**Describe the solution you'd like**
The most straightforward solution would be for the apps CLI to inline a certain subset of environment variables in the built app. For example any variables prefixed with `STRIPE_PUBLIC_` (following the pattern established by Next, Vite and Snowpack)

**Describe alternatives you've considered**
If environment variables are considered too leaky even with the prefix, flags could be restricted to those made explicit in the command line, for example executing `stripe-preview apps start --flags MOCK_ENV=true`

**Comment by mbicknese** [comment]
I am getting back to this as we've stumbled on a new use case.

Being able to hoist environment variables into the transpiled/bundled app code is the base request. Just the current environment from which `stripe apps start` or `stripe apps upload` is run would be a great start. Leveraging dotenv is a welcome addition as it makes it simpler for developers to run the app consistently.

**Comment by ericfrank-stripe** [comment]
We just shipped a solution for switching values in local development: https://stripe.com/docs/stripe-apps/reference/app-manifest#extended-manifest
