### ISSUE TITLE
Connect Extension Migration Story

### ISSUE THREAD

**Issue by mjohnsonpint-stripe** [stripe/stripe-apps#210]
Currently the install process for connect extension starts on the partner site and ends on the partner site. We are inverting this flow to start and end on the Stripe marketplace. Partners have expressed both confusion about this change, and dissatisfaction with the change in workflow. Dissatisfaction is rooted in:
    - Technical limitations around changing from receiving an oAuth callback to listening to a webhook event
    - Dissatisfaction with the move of the customer off of the partner’s platform and onto ours
    - Confusion around how to install UI extensions on ‘both’ sides (in their UI and ours)

**Comment by clement911** [comment]
Our issue with post install action linking to an external url is that we can only provide a static url in the manifest.
We need to pass dynamic state similar to the oAuth state parameter from the [Connect OAuth ref](https://stripe.com/docs/connect/oauth-reference
).
