### ISSUE TITLE
Use third-party inline scripts (Content Security Policy)

### ISSUE THREAD

**Issue by zavjs** [stripe/stripe-apps#225]
## Your Problem

I'd like to use the Google Tag Manager inline script to log user actions throughout my Stripe app. 

- I tried allowing the source (https://googletagmanager.com/) by altering the “connect-src”, "script-src” and “script-src-elem” directives in the content_security_policy section in the stripe-app.json file, but that doesn't seem to work. I get:
> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src"

## Existing Documentation URLs (If applicable)
https://stripe.com/docs/stripe-apps/extend-dashboard-user-interface#use-third-party-apis

The only documentation available refers to how to extend third party APIs, not scripts.

**Comment by cchalstrom-stripe** [comment]
This is something we don't currently plan on supporting.  Any scripts included would need to be imported using `import` statements.
