### ISSUE TITLE
Payment Metadata In Payment list and details

### ISSUE THREAD

**Issue by mjohnsonpint-stripe** [stripe/stripe-apps#25]
It would be cool to be able to add some additional metadata to a payment inline in the payment list UI. 

The specific use case this comes from is commissions - in many cases payments represent a commission owed to someone else. It would be nice to be able to show on the payment 'x$ commission to Joe Sales Person'

There are probably other use cases for this.

**Comment by ericfrank-stripe** [comment]
Closing this issue as the information requested is available from the viewport context using the API.
