### ISSUE TITLE
SparkLine style line charts

### ISSUE THREAD

**Issue by gwatts-klipfolio** [stripe/stripe-apps#263]
**Is your feature request related to a problem? Please describe.**
The LineCharts and BarCharts currently take up a lot of vertical space, which makes it difficult to fit the information needed into the sidepanel for the app. The use case we have only requires showing a general trend of the data rather than providing a data display. 

**Describe the solution you'd like**

We would like to be able to set options on these charts to:

- Decrease the vertical size to about half of the total height
- Remove the X and Y axes of the visualization

Note: We would still like to be able to tell where the 0 point is on the Y axis, either by showing the 0 line if the line crosses the 0 point, or by using an area style instead. 

**Describe alternatives you've considered**

We don't have a viable alternative that allows us to use charts while reducing the vertical space. We have tried constraining the charts using a Box with a set height, but the charts still render to the same size.

**Additional context**

An example of a current chart:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/25153757/157750955-a8b1a2e3-4945-4dd6-81f4-ff4ac6ff54b2.png">

An example of a desired chart:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/25153757/157750978-263a1c33-4eac-4124-91f0-35c1cc9d711d.png">

**Comment by jackokerman-stripe** [comment]
@gwatts-klipfolio, We added a new chart component for this in the latest SDK release. Take at the docs for [Sparkline](https://stripe.com/docs/stripe-apps/components/sparkline).
