### ISSUE TITLE
UI Testing Reference: debug allProps modifier documentation out of date & issue with option.

### ISSUE THREAD

**Issue by lyndseybrowning** [stripe/stripe-apps#299]
**Describe the bug**

The documentation for the `debug` method found in the [UI Testing Reference Documentation](https://stripe.com/docs/stripe-apps/reference/ui-testing#element-properties-and-methods), says there is an `allProps` option that allows users to modify which props are output by the debugger. It looks like this prop has been changed to `all`, and the documentation is not up to date.

Secondly, the `all` prop is said to ***"overrides the default props filtering behaviour and instead includes all props in the output. By default, className, aria-*, and data-* props are omitted."* However, it doesn't look like this option is taking effect, and those props are still available in the output.

I've got a very basic example component:

```js
<List aria-label={ariaLabel}>
  <ListItem title="My List Item" />
  <Button className="my-button" onPress={() => null}>
    This is a button
  </Button>
</List>
```

With the following test:

```js
const { wrapper } = render(
  <SimpleToDoList aria-label="A simple to do list" />
);

console.log(wrapper.debug({ all: false }));
```

And I get this output in the console: 

```js
<List aria-label="A simple to do list">
 <ListItem title="My List Item" />
 <Button className="my-button" onPress={[Function onPress]}>
   This is a button
 </Button>
</List>
```

Should I expect the aria-* and className props to be omitted in the output or am I misunderstanding this option?

**Note** that the output is always the same whether `all` is set to `true` or `false`.

**Additional context**

```json
"dependencies": {
    "@stripe/ui-extension-sdk": "^3.1.0",
    "react": "^17.0.2",
    "stripe": "^8.191.0"
  },
  "devDependencies": {
    "@types/jest": "^27.4.0",
    "jest": "^27.4.7",
    "ts-jest": "^27.1.3",
    "ts-node": "^10.4.0",
    "typescript": "^4.6.2"
  },
```

**Comment by jackokerman-stripe** [comment]
@lyndseybrowning the `all` modifier has been fixed in the latest release of `@stripe/ui-extension-sdk` so that filtering works properly, and [the name has been updated in the docs](https://stripe.com/docs/stripe-apps/ui-testing#element-properties-and-methods).
