### ISSUE TITLE
Strategies for handling multiple environments?

### ISSUE THREAD

**Issue by balvig** [stripe/stripe-apps#303]
Are there are any recommended ways for configuring the apps to f.ex run against a staging environment?

In particular I'm wondering how to:

1. Configure the URLs in `content_security_policy` dynamically
2. Dynamically set variables based on an f.ex an ENV variable

## 1. Configuring `content_security_policy`

For this, currently we're manually editing `stripe-app.json`, so for example:

```json
    "content_security_policy": {
      "connect-src": [
        "https://staging.myapp.com/stripe/api"
      ],
```

becomes:

```json
    "content_security_policy": {
      "connect-src": [
        "https://production.myapp.com/stripe/api"
      ],
```

etc. 

Is there a better approach? Would it be reasonable to f.ex add both staging and production URLs to `content_security_policy`, or would that cause issues in review later?

## 2. Dynamically setting variables

We have something like this in the app code:

```js
const API_HOST = "https://staging.myapp.com"
// const API_HOST = "https://production.myapp.com"
```

In a plain Node app, it's common to see something like https://www.npmjs.com/package/dotenv to handle this, but I'm not sure how we would configure and make use of `process.env` in a Stripe App?

**Comment by ericfrank-stripe** [comment]
We just shipped a solution for switching values in local development: https://stripe.com/docs/stripe-apps/reference/app-manifest#extended-manifest

A solution for test channels is also being developed.

**Comment by robert-moore** [comment]
This is awesome. Are there any recommendations or examples around patterns to use constants outside of React components. My guess is that most developers have patterns similar to @balvig above https://github.com/stripe/stripe-apps/issues/303#issue-1176427753

So the pattern of grabbing environment.constants and passing it every time to an app code function with all the API calls would be error prone. Many thanks

**Comment by ericfrank-stripe** [comment]
@robert-moore We only support constants used within React components (or passed from components to utility functions) today, but we've received the feedback that it would be useful to have these constants in some kind of an accessible global variable. I've opened a new issue for that here: https://github.com/stripe/stripe-apps/issues/775

Thanks for your feedback!
