### ISSUE TITLE
Lazy loading tab panels

### ISSUE THREAD

**Issue by cmmartin** [stripe/stripe-apps#307]
**Is your feature request related to a problem? Please describe.**

I was surprised to find that all tab panels are mounted simultaneously, despite only one being visible. This prevents us from lazy loading data in tabs that are infrequently opened.

**Describe the solution you'd like**

I want only the currently selected (active) tab panel's children to be mounted, so I don't have to load all data for all tabs when the app screen first loads. The current behavior leads to a weird state where the DOM has been removed, but the component has not unmounted (no cleanup functions in `useEffect` have run, so async tasks cannot be cancelled if the user navigates away from that tab)

**Describe alternatives you've considered**

I thought I could use `selectedKey` and `onSelectionChange` to conditionally render the children...

```jsx
<TabPanel>{selectedKey === 'some-key' && <PanelChildren />}</TabPanel>
```

however, the `selectedKey` does not match the value passed to it. If you pass `selectedKey={0}`, the key is set to `$.0` at runtime. Consequently, this means the tabs are not actually "controlled" and you cannot set the default tab to anything but the first one

**Additional context**

To reproduce...

```jsx
export default function TestApp() {
  const [key, setSelectedKey] = React.useState<string | number>(1)
  console.log(key)
  return (
    <ContextView title="Test">
      <Tabs
        fitted
        selectedKey={key}
        onSelectionChange={setSelectedKey}
      >
        <TabList>
          {[1, 2].map((i) => (
            <Tab key={i}>Tab {i}</Tab>
          ))}
        </TabList>
        <TabPanels>
          {[1, 2].map((i) => (
            <TabPanel key={i}>
              <ExamplePanel>{i}</ExamplePanel>
            </TabPanel>
          ))}
        </TabPanels>
      </Tabs>
    </ContextView>
  )
}

function ExamplePanel({ children }) {
  React.useEffect(() => {
    console.log(`tab ${children} mounted`)

    return () => {
      console.log(`tab ${children} unmounted`)
    }
  }, [children])

  return children
}
```

If you run the code above, you can see from the log statements that all tabs mount on initial render and no tabs ever unmount

**Comment by cchalstrom-stripe** [comment]
@cmmartin we have released a new [SDK version v8.2.0](https://www.npmjs.com/package/@stripe/ui-extension-sdk) to address the issue you raised about `selectedKey` not working.

Please let us know if this resolves your issue.  Thanks for reporting!
