### ISSUE TITLE
TabPanel child component not being re-rendered after state change

### ISSUE THREAD

**Issue by dariodjuric** [stripe/stripe-apps#326]
**Describe the bug**

When a child component of `TabPanel` returns its elements within template fragments, the component will not be re-rendered if its state changes. The `TabPanel` will show the component in its initial state. If on the other hand, the child component returns its element wrapped in a parent element like `Box`, everything will work fine.

I am not sure if this is considered a bug or not. If not, perhaps this edge-case can be mentioned in the docs?

**To Reproduce**

Create a view that has a component like `ContactDetails` below:

```
import {
  Box,
  Inline,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
} from '@stripe/ui-extension-sdk/ui';
import React, { useEffect, useState } from 'react';
import { Inbox } from '../inbox/components/Inbox';

export const DumbComponent = () => {
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => {
    setTimeout(() => {
      console.log('Timeout done');
      setMessage('Loaded');
    }, 3000);
  });

  return (
    <>
      {!message && <Inline>Loading message</Inline>}
      {message && <Inline>{message}</Inline>}
    </>
  );
};

export const ContactDetails = () => {
  return (
    <Tabs size="small" fitted>
      <TabList>
        <Tab key={1}>Conversations</Tab>
        <Tab key={2}>About</Tab>
      </TabList>
      <TabPanels>
        <TabPanel key={1}>
          <DumbComponent />
        </TabPanel>
        <TabPanel key={2}></TabPanel>
      </TabPanels>
    </Tabs>
  );
};

```

This part is causing the issue:

```
  return (
    <>
      {!message && <Inline>Loading message</Inline>}
      {message && <Inline>{message}</Inline>}
    </>
  );
```

If we replace it with the following, everything will work properly.

```
  return (
    <Box>
      {!message && <Inline>Loading message</Inline>}
      {message && <Inline>{message}</Inline>}
    <Box/>
  );
```

**Expected behavior**

`DumbComponent` should be re-rendered properly after its state has been changed.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 99+ (latest)
 - Stripe SDK version: 4.0.0

**Comment by ericfrank-stripe** [comment]
We've determined that this is an architectural issue involving the interaction of two core libraries that we use that can't be easily patched. Since there is a simple workaround, we've documented it on the tab component page:

https://stripe.com/docs/stripe-apps/components/tabs#unsupported-uses

I'm closing this issue for now, but we'll continue to evaluate a permanent fix as our libraries update.
