### ISSUE TITLE
Automatic "external" icons in external links

### ISSUE THREAD

**Issue by vrugtehagel** [stripe/stripe-apps#438]
**Is your feature request related to a problem? Please describe.**
We were told in the quality review that external links should have the external icon appended. It's a bit verbose to have to manually add the icon to every external link, so in order to not repeat ourselves, we need a wrapper component for external links. It'd be great if this was a feature in the `Link` component itself.

**Describe the solution you'd like**
If all external links should have this icon with no exceptions, it would be ideal for the `Link` component itself to determine whether or not the link is external, and add the icon if it is. That way, it requires no additional work for developers and enforces this design guideline automatically.

**Describe alternatives you've considered**
Alternatively, if automatic detection is not an option, then an additional prop `external` would be a solution as well. That way, developers can mark their links as external without having to import the `Icon` component and write `<Icon name="external" size="xsmall"/>`, and we wouldn't have to worry about whitespace and/or adding left margins to the icon to offset it from the text somewhat.

**Additional context**
The header already does this automatically:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/41021050/165055701-a828e25a-ad13-4719-9774-87a1b218435e.png">

Unfortunately, just writing external URLs like below looks slightly off compared to the header:
```
<Link href="#">
  External service <Icon name="external" size="xsmall"/>
</Link>
```

<img width="159" alt="image" src="https://user-images.githubusercontent.com/41021050/165055459-ddc24a56-0e87-4d22-9f27-915f90350469.png">

**Comment by cchalstrom-stripe** [comment]
This is now available in [v8.2.0 of the sdk](https://www.npmjs.com/package/@stripe/ui-extension-sdk).
[Docs](https://stripe.com/docs/stripe-apps/components/link#primary-link)

```
<Link href="https://www.example.com/" external>External primary link</Link>
```

Thanks for the suggestion!
