### ISSUE TITLE
Retrieving connected accounts raises permission error

### ISSUE THREAD

**Issue by kylefox** [stripe/stripe-apps#458]
**Describe the bug**

Previously, when an account was authorized using the Connect OAuth flow, the account details could be fetched using the [retrieve account](https://stripe.com/docs/api/accounts/retrieve?lang=ruby) endpoint:

```ruby
Stripe::Account.retrieve("acct_abc123")
# => <Stripe::Account id=acct_abc123>
```

However, after connecting an account by installing the Stripe App, this API call now raises a `Stripe::PermissionError`:

```ruby
Stripe::Account.retrieve("acct_abc123")
# => Stripe::PermissionError ((Status 403) (Request req_Z1qph5bRRnifof)
# => This application does not have the required permissions for this endpoint on account 'acct_abc123'.
# => Having the 'read_only' scope would allow this request to continue.)
```

`account_read` is not an [available permission](https://stripe.com/docs/security/permissions) our Stripe App can request, so currently there is no way for us to fetch account details for these merchants.

(Note that we are still able to make _other_ API calls related to the connected account. For example `Stripe::Customer.list({}, stripe_account: 'acct_abc123')` works as expected).

**To Reproduce**
1. Install the Stripe App into an account (ex: acct_abc123)
2. Attempt to fetch account details via API (ex: `Stripe::Account.retrieve('acct_abc123')` in Ruby)
3. `Stripe::PermissionError` is raised

**Expected behavior**

Calling `Stripe::Account.retrieve('acct_abc123')` after installing the app returns the [account object](https://stripe.com/docs/api/accounts/object?lang=ruby).

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by iuricmp** [comment]
@kylefox I'm still facing this issue with NodeJS SDK `8.216.0`.

I've granted the `connected_account_read` permission into `stripe-app.json` and installed the App into another account (not the same account that owns the app).

Additional note: I'm testing into an Account that has 3 Accounts linked to it. eg:
<img width="354" alt="Screenshot 2022-05-25 at 17 01 32" src="https://user-images.githubusercontent.com/689440/170306884-4260a3f4-ef6a-4ba1-8f36-5078c2516a55.png">
