### ISSUE TITLE
Installed app tries to reach out to a stripe url and breaks the app

### ISSUE THREAD

**Issue by TapaiBalazs** [stripe/stripe-apps#468]
**Describe the bug**
Our app is installed to the account where we published it. While testing it, after an action the app tries to reach out to:
`https://b.stripecdn.com/manage-statics-srv/assets/dashboard.vendors~extension_runtime.b40b1b6b5aa5168f2d14.min.js` which gets refused with the message:

```
Refused to connect to 'https://b.stripecdn.com/manage-statics-srv/assets/dashboard.vendors~extension_runtime.b40b1b6b5aa5168f2d14.min.js' because it violates the following Content Security Policy directive: "connect-src http://localhost:* localhost:* https://intercom.thisdotstripeapps.com/api/".
```

After that our app completely breaks, and we get a message in our console with the following content: 
```
[Stripe App app.id.redacted] Error: Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Please reach out to us if you need a demonstration.
Sadly, the app installed to other accounts has other issues that prevents reproducing this exact error on another stripe account. 

**Expected behaviour**
assets that are required for the Stripe app, are automatically updated with the content-security policy

**Screenshots**
![Screenshot 2022-05-02 at 14 46 42](https://user-images.githubusercontent.com/13385210/166235951-0b0450f0-f9f4-4c24-98db-6733bc929ce8.png)
![Screenshot 2022-05-02 at 14 43 16](https://user-images.githubusercontent.com/13385210/166235958-4699956b-a709-495a-a27a-035dcedc4f45.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - MacOS
 - Browser [e.g. chrome, safari] - Chrome
 - Version [e.g. 22] - Latest, 100+
 - SDK version for the published app: 6.3.0

**Additional context**
Everything worked last Friday morning and I can't reproduce this error in local development mode.

**Comment by ericfrank-stripe** [comment]
This issue should now be resolved. Please comment here if it recurs.

**Comment by TapaiBalazs** [comment]
It is fixed, yes. Thanks!
