### ISSUE TITLE
Expose `textAlign` property for `Box` components

### ISSUE THREAD

**Issue by ahhreggi** [stripe/stripe-apps#476]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to center-align text within a `Box` component but the `textAlign` property is currently not supported.

**Describe the solution you'd like**
Add `textAlign` as a valid css prop to the `Box` component (and maybe `Inline`?)

**Describe alternatives you've considered**
I've tried breaking up long strings of text into shorter strings and then using `alignX: 'center'` on each one. It works, but it seemed like overkill for just trying to find a workaround to a single css property that could do the job.

**Comment by jackokerman-stripe** [comment]
@ahhreggi, we added `textAlign` to the `Box` component with our [latest release](https://www.npmjs.com/package/@stripe/ui-extension-sdk), so you can now do the following:
```tsx
<Box css={{textAlign: 'center'}}>
  Box where text is centered
</Box>
```
There's some more info in the docs [here](https://stripe.com/docs/stripe-apps/style#text-overflow,-wrapping,-transformation,-and-alignment).
