### ISSUE TITLE
ButtonLink component is shown in the Figma library but not available in the SDK 

### ISSUE THREAD

**Issue by sswebster** [stripe/stripe-apps#482]
**Describe the bug**
There is a ButtonLink component shown in the Figma files that is not available in the SDK. When I try to import `ButtonLink` from the SDK I receive the error `@stripe/ui-extension-sdk/ui' has no exported member 'ButtonLink'.`

**To Reproduce**
1. Try to import `ButtonLink` from `@stripe/ui-extension-sdk/ui` into a view
2. See the error

**Expected behavior**
It looks to me like this is an intended component (see screenshot from Figma) so it should be exposed to be imported. Or if it is no longer on the roadmap it should be removed from Figma.

**Screenshots**
![CleanShot 2022-05-03 at 14 56 17@2x](https://user-images.githubusercontent.com/8900751/166692152-63354494-be7a-47e5-b882-e54e6a519128.jpg)

**Desktop (please complete the following information):**
 - iOS 12.2.2.1
 - Chrome 100.0

**Comment by jasontang-stripe** [comment]
The component now is called `link`. You can find the doc here. https://stripe.com/docs/stripe-apps/components/link
We will update the Figma library to match the name.
