### ISSUE TITLE
Duplicate elements appear if the app and settings are opened at the same time 

### ISSUE THREAD

**Issue by jimthoburn** [stripe/stripe-apps#493]
**Describe the bug**
If I open the app and the settings page at the same time, and if either of them re-render an element based on changing state; that element has a duplicate rendering.

This may be related to https://github.com/stripe/stripe-apps/issues/305

**To Reproduce**

1. Add the following to your `stripe-app.json` file:
```
{
  "viewport": "stripe.dashboard.drawer.default",
  "component": "DefaultView"
},
{
  "viewport": "settings",
  "component": "SettingsView"
}
```

2. Create a file named `/views/SettingsView.tsx` with the following code:
```
import { useState, useEffect } from "react";
import { SettingsView, Box } from "@stripe/ui-extension-sdk/ui";

const Settings = () => {
  const [state, setState] = useState("loading");

  useEffect(() => {
    if (state === "loading") {
      setState("connected");
    }
  }, [state, setState]);

  console.log({ settings: 1, state });

  return (
    <SettingsView
      onSave={() => {
        // Nothing to save
      }}
    >
      <Box>Hello from the settings view 👋</Box>
      {state === "connected" && <Box>Settings view is connected ✅</Box>}
    </SettingsView>
  );
};

export default Settings;
```

2. Create a file named `/views/DefaultView.tsx` with the following code:
```
import { useState, useEffect } from "react";
import { ContextView, Box } from "@stripe/ui-extension-sdk/ui";

const DefaultView = () => {
  const [state, setState] = useState("loading");

  useEffect(() => {
    if (state === "loading") {
      setState("connected");
    }
  }, [state, setState]);

  console.log({ app: 1, state });

  return (
    <ContextView title={"Test app (not in use)"}>
      <Box>Hello from the app 👋</Box>
      {state === "connected" && <Box>App is connected ✅</Box>}
    </ContextView>
  );
};

export default DefaultView;
```

4. Upload the app.
5. Switch off “app preview”.
6. Open the app and wait for the “App is connected” message to appear.
7. Use the “ellipsis” menu button in the app to open the settings page.
8. Wait for the “Settings view is connected” message to appear.
9. If this test worked, you’ll see the message rendered more than once in the `SettingsView`.
10. Refresh the page.
11. Wait for the “Settings view is connected” message to appear.
12. Open the app, and wait for the “App is connected” message to appear.
9. If this test worked, you’ll see the message rendered more than once in the `DefaultView`.

**Expected behavior**
Duplicate components don’t appear, when I open the settings and the app at the same time.

**Screenshots**
<img width="1349" alt="settings" src="https://user-images.githubusercontent.com/926616/166849696-fe4a36b0-9588-4030-b830-82b5692c4689.png">

<img width="1349" alt="app" src="https://user-images.githubusercontent.com/926616/166849701-0a321ac1-2acf-4937-b9df-22d974564de3.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.6.5
 - Browser: Chrome
 - Version: 100.0.4896.127

**Additional context**
If I don’t open the app while on the settings page, everything works well and this bug doesn’t happen.

**Comment by ericfrank-stripe** [comment]
We just pulled in a patch in one of our dependencies that should fix the majority of these duplicate content type rendering issues. I'll close this ticket, but feel free to comment if you continue to experience issues.
