### ISSUE TITLE
Breadcrumb component not showing app name

### ISSUE THREAD

**Issue by vrugtehagel** [stripe/stripe-apps#494]
**Describe the bug**
Although the `stripe-app.json` has a `name` key, it does not show up for me in the breadcrumbs on the https://dashboard.stripe.com/settings/apps/[app-id] page and instead shows `{appName}`. My colleague however sees the name correctly (they're on the same account, looking at the same app).

<img width="356" alt="image" src="https://user-images.githubusercontent.com/41021050/166881128-1389b395-26fc-4cb3-887e-29d2fdbdef09.png">

**To Reproduce**
Unclear; for me, it always shows `{appName}`, and my colleague reports never having seen this on their end.

**Expected behavior**
I expect to see the app name correctly.

**Desktop (please complete the following information):**
For me:
 - OS: MacOS Monterey (12.3.1)
 - Browser Chrome
 - Version 100.0.4896.127 (Official Build) (x86_64) 

My colleague:
 - OS: MacOS Big Sur (11.6.5)
 - Browser Chrome
 - Version 100.0.4896.88 (Official Build) (x86_64)

**Comment by ngrubb-stripe** [comment]
I haven't been able to recreate this issue and occurrences of it have not been reported to us in some time. Closing this issue, but feel free to open a new issue if this problem occurs again.

**Comment by TapaiBalazs** [comment]
@ngrubb-stripe I have been able to reproduce this just now.

**Steps to reproduce:**
1. Open an account that is activated and has an app installed in them.
2. Open the app
3. Click on the `...` menu and select `View App Settings`
4. Stripe navigates you to the app settings page

**What happens:**
{appName} is in the breadcrumbs and in the browser tab title

**What should happen:**
The application's name should be displayed in the browser tab title and in the breadcrumbs.

**Comment by ngrubb-stripe** [comment]
Thanks @TapaiBalazs! We were able to identify the issue and we have just deployed a fix.
