### ISSUE TITLE
Do not show `0` in <LineChart /> tooltip when no value

### ISSUE THREAD

**Issue by bumblingbuffalo** [stripe/stripe-apps#497]
**Describe the bug**
when using the line chart with more than one set of data the tooltip will show `0` if data is missing for a given x value.

**To Reproduce**
```
    <LineChart
      data={[
        { Spend: 200, date: 1, label: 'A' },
        { Spend: 400, date: 2, label: 'A' },
        { Spend: 500, date: 3, label: 'A' },
        { Spend: 500, date: 4, label: 'A' },
        { Spend: 500, date: 5, label: 'A' },
        { Spend: 500, date: 6, label: 'A' },
        { Spend: 300, date: 1, label: 'B' },
        { Spend: 600, date: 2, label: 'B' },
      ]}
      x={{ value: 'date' }}
      y={{ value: 'Spend', format: { currency: 'USD' } }}
      color='label'
    />
```

**Expected behavior**
If there is not a y value for a given x, do not show the item in the tooltip

**Screenshots**
![May-05-2022 12-01-37](https://user-images.githubusercontent.com/97477645/166964770-3cfe2be9-6809-40f9-a497-6853a54f667d.gif)

**Comment by ericfrank-stripe** [comment]
This issue should be resolved now, no SDK update required. Thank you for your patience.
