### ISSUE TITLE
ability to prompt the user for confirmation before closing a focus view

### ISSUE THREAD

**Issue by tma-stripe** [stripe/stripe-apps#52]
Trigger a prompt when the user attempts to close the drawer, and ask them to confirm before closing

**Comment by Rajkiran0147** [comment]
The confirmation dialog does not show up on closing the focussed view by clicking the X at the top or when we have a secondary action like cancel. It works only when focussed view is closed by clicking outside or pressing escape. Can this be fixed to make the conformation dialog appear on all focussed view closing scenarios ?

**Comment by ericfrank-stripe** [comment]
@Rajkiran0147 Thanks for this note. I've opened up a new issue and you can track progress there: https://github.com/stripe/stripe-apps/issues/651
