### ISSUE TITLE
Info about distribution (private/public) is not consistent on app list and app details page.

### ISSUE THREAD

**Issue by whobubble** [stripe/stripe-apps#520]
**Describe the bug**
Info about distribution (private/public) is not consistent on app list and app details page.

**To Reproduce**
1. Upload an app and choose distribution to be "Public"
2. Go to /apps
3. Click on 'My Apps'
4. Notice the entry in the list shows distribution as "Private"
5. Click on the app
6. Notice in the app details page shows distribution as "Public"

**Expected behavior**
The list entry should show "Public" for apps that have distribution set to "Public"

**Screenshots**
Apps list
![2022-05-10_09-01](https://user-images.githubusercontent.com/15037/167567864-bcc34ddb-e7a6-4f21-9670-2b8a340ae8a0.png)

App detail 
![2022-05-10_09-03](https://user-images.githubusercontent.com/15037/167568189-a6517de2-c5cc-4e32-8771-8d321ee2b9d8.png)
page

**Desktop (please complete the following information):**
 - OS: MacOS 11.6 Big Sur
 - Browser: Chrome
 - Version: 94.0.4606.71

**Comment by ngrubb-stripe** [comment]
We have resolved this issue. The list will now track your distribution selection and show selection to avoid confusion. Thanks for reporting!
