### ISSUE TITLE
UI Component: Toast

### ISSUE THREAD

**Issue by tma-stripe** [stripe/stripe-apps#53]
The capability to send a confirmation toast upon user action. An example is the Alert Dialog https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/alertdialog.html

**Comment by griffink-stripe** [comment]
The toast component is in the Docs but when I attempt to import `import {showToast} from '@stripe/ui-extension-sdk/utils';
` it does not show up as existing.

**Comment by ericfrank-stripe** [comment]
@griffink-stripe It's working on my end. What version of `@stripe/ui-extension-sdk` are you on?

**Comment by griffink-stripe** [comment]
Bingo that was it! I thought I upgrade but realize I updated the CLI not the package.json. My bad!
