### ISSUE TITLE
Improve docs on why CORS is needed for app backend

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/stripe-apps#533]
From Implementation review:

The cross origin policy is a major gotcha for backends. 

We should explicitly mention this in https://stripe.com/docs/stripe-apps/build-backend and provide sample code in more than one language. The [interactive webhook builder ](https://stripe.com/docs/webhooks/quickstart)we link to does not handle this (at least in Python / Flask, I didn’t try others).

**Comment by ericfrank-stripe** [comment]
That page has been updated with more information about our CORS policy.
