### ISSUE TITLE
The top of the “Save changes” button is clipped on the settings page

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/stripe-apps#540]
From Implementation review:

The top of the “Save changes” button is clipped on the settings page

**Comment by ngrubb-stripe** [comment]
We have added a fix for this issue and it is now deployed: 

<img width="848" alt="Screen Shot 2022-06-14 at 3 52 20 PM" src="https://user-images.githubusercontent.com/89162925/173676675-1e6bb8a3-9a8c-4405-a42f-9b5b57facc26.png">
