### ISSUE TITLE
Apps that have long names break header layout.

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/stripe-apps#551]
**From Implementation review:**

Apps that have long names break header layout.

Buttons … and X lose spacing gets collapsed when the title expands. 

**Long title**
![image](https://user-images.githubusercontent.com/53238203/168125164-9b6fdfc8-b44f-4a59-aea4-1fccec29d289.png)

**Normal**
![image](https://user-images.githubusercontent.com/53238203/168125184-7f6c3eeb-ccb1-46c3-a15a-dcb8150fbbec.png)

**Comment by sandhyaj-stripe** [comment]
We've deployed app name truncation with full name showing on hover. Resolving this issue.
