### ISSUE TITLE
Inconsistent layout of success / error screens.

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/stripe-apps#557]
Inconsistent layout of success / error screens.

Consider using same layout for all.

FWIW I prefer the layout of the centered screens but prefer the icon treatment of the first one (left aligned).

![image](https://user-images.githubusercontent.com/53238203/168193503-0cbd0d02-fe1e-4fc7-845c-b0e38b30d056.png)
![image](https://user-images.githubusercontent.com/53238203/168193509-ab0fb459-13b7-4b8e-adc2-be5bbff9d041.png)
![image](https://user-images.githubusercontent.com/53238203/168193514-5a0ae433-277a-4c77-a950-45a05a4e1473.png)

**Comment by ngrubb-stripe** [comment]
We have updated these content states to be more consistent between CLI & Stripe Apps stand-alone pages.
