### ISSUE TITLE
Featured apps label / CTA

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/stripe-apps#558]
Featured apps label / CTA

On first run I didn’t understand what this was…

Even then I’m not sure it’s the best call to action. Does it capture my intent?

🤔 Should this be titlecase? I’m assuming Apps is considered a proper noun?

![image](https://user-images.githubusercontent.com/53238203/168193600-634a9427-5d28-4771-b455-0b3ebaec8e33.png)

**Comment by jasontang-stripe** [comment]
Label has updated to "Stripe Apps".
