### ISSUE TITLE
View app details menu option is available for public apps

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/stripe-apps#568]
View app details menu option is available for public apps, which shouldn't be the case, as this app is installed from the marketplace, and therefore the merchant don't have it under their developer settings.

<img width="1269" alt="Screen Shot 2022-05-13 at 11 29 41 AM" src="https://user-images.githubusercontent.com/53238203/168345402-63b7b5be-e9a2-4437-93d6-a667b19d8418.png">

**Comment by dannygarcia-stripe** [comment]
Yup! Closing
