### ISSUE TITLE
`stripe apps start` sometimes grabs an in-use port and gives confusing errors

### ISSUE THREAD

**Issue by natw-stripe** [stripe/stripe-apps#588]
**Describe the bug**
There are some cases where you can run `stripe apps start` without error even though you already have an application running on port 4242. When this happens you immediately get stuck on the devmode screen with an error and no useful information:

<img width="555" alt="Screen Shot 2022-05-18 at 5 42 09 PM" src="https://user-images.githubusercontent.com/94389513/169160657-173657a9-4245-40c6-9865-8390f1c2ed4a.png">

**To Reproduce**
I can't repro this by running `stripe apps start` twice, but it repros every time with an Express.js app and `stripe apps start`.

1. Run an express app, e.g. the Secret Store backend app. `node app.js`
2. Run `stripe apps start` in a UI extension dir. It'll run without error and tell you to hit enter.
3. Hit enter and see the error screen.

**Expected behavior**
`stripe apps start` should fail to start if something already has the port

**Screenshots**
See above.

**Desktop (please complete the following information):**
OS: MacOS 12.3.1
Browser: Chrome 101.0.4951.64
CLI: 1.8.8
Apps plugin: 1.2.0

**Additional context**

**Comment by mauryaratan** [comment]
Same issue here! A quick resolution would be really handy here 🙌🏻

**Comment by ericfrank-stripe** [comment]
The CLI now returns the error:
```
error starting dev server: localhost:4242 is already in use
Are you running stripe apps start on another terminal?

😔 Failed to start development server.
```
