### ISSUE TITLE
account.application.deauthorized webhook is not triggering

### ISSUE THREAD

**Issue by rompas** [stripe/stripe-apps#596]
Created a webhook for the `account.application.deauthorized` event on the account that publishes the app (A), and installed then uninstalled the app from a different account (B). When looking at the Events section for account B I see the deauthorized event, but the webhook in account A is not triggering

**Comment by chaves-stripe** [comment]
hi @rompas.. were you able to check if your app was requesting `event_read` permission?

**Comment by rompas** [comment]
Hi @chaves-stripe. The app is now requesting the `event_read` permission, but webhook is still not triggering:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/15014503/173232600-f1caceb1-6726-43d7-ad30-4db7bf5eb723.png">

**Comment by chaves-stripe** [comment]
hi @rompas ... Can you confirm the account ID that you created the Webhook Endpoint hat listens for this event on? thanks!

**Comment by rompas** [comment]
<img width="829" alt="image" src="https://user-images.githubusercontent.com/15014503/173773908-f6ad3fce-7783-471c-9a79-382a8ff4c644.png">
Seems so, tried on both test and live modes

**Comment by rompas** [comment]
Ah sure! it's `acct_16ft4UExQxdrnKcK`

**Comment by chaves-stripe** [comment]
@rompas after taking a look at your app, my current hunch of what is happening for you is that merchant B installed the app but the _older_ version, which did not have the event_read permission. In order for the event to go through, they will need to reinstall once your app version with `event_read` is approved in the marketplace. Can you let me know the account ID for merchant B so that I can verify this is correct?

**Comment by rompas** [comment]
Ahh I see. We talked with the team and they installed the up to date version for our user with `event_read` permission, but still now luck.

account id: `acct_1KlpxoEcbIGVQdEl`

**Comment by jcipriano-stripe** [comment]
Hi @rompas, can your reach out to your private beta partnership manager and partner engineer through email. We'll work with you directly to unblock you here. Thanks!
