### ISSUE TITLE
Layout crashes when system fails to reuse components

### ISSUE THREAD

**Issue by mbicknese** [stripe/stripe-apps#606]
**Describe the bug**

It seems that the layout system tries to optimize by reusing already rendered components. But when it falsely detects the same component already being present, by confusing it with another, the layout crashes.

There needs to be a conflicting prop.

**To Reproduce**

```jsx
const PaymentListView = () => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => setLoading(false), 500); // simulating a trigger which re-renders the component
  });

  return (
    <ContextView title="Minimal bug reproduction example">
      {loading ? (
        <Box css={{ stack: "x" }}>Now you see me.</Box>
      ) : (
        <Box css={{ marginTop: "medium" }}>Now you don't!</Box>
      )}
    </ContextView>
  );
}
```

**Expected behavior**

The different states of the view to be rendered without crashing. The layout is valid, which can be tested by rendering them separately without switching.

**Desktop (please complete the following information):**

This seems to be an environment-independent issue. Tested on

 - OS: macOS 12.4
 - Browser Firefox
 - Version 100.0.2

**Additional context**

One can work around this issue by putting `keys` on the conflicting components, or by wrapping them in a `Box` with different `keys`.

**Comment by mjohnsonpint-stripe** [comment]
@rfelix2121 have you tried the work-around of adding a key described in the issue? Does that unblock you?

**Comment by rfelix2121** [comment]
@mjohnsonpint-stripe

I’m not currently being affected by this. I ended up deleting the affected code altogether in order to make the Sessions announcement. Thanks!

**Comment by ericfrank-stripe** [comment]
We've merged a fix for this issue in a future release of the Dashboard (no app changes required). I'll update this issue when it's out.
