### ISSUE TITLE
Can't publish approved App to marketplace

### ISSUE THREAD

**Issue by davidmennie** [stripe/stripe-apps#610]
**Describe the bug**
We cannot publish the approved version of our app to the marketplace. We received the "approved for Sessions Announcement" email and we've attempted to follow the guide you provided (https://stripe.com/docs/stripe-apps/marketplace/publish-app), however, there is no "Review and publish" link/button or "Publish" button as described.

**To Reproduce**
1. Login to the Stripe Dashboard developer account
2. Click on our app listing

There is no "Review and publish" or "Publish" button as described in the docs.

**Expected behavior**
We can review and publish our approved app version to the marketplace. Currently, we have version 1.7.3 of our app in the marketplace even though 1.8.2 was approved.

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 101.0.4951.64 (Official Build) (x86_64)

![Developers section](https://user-images.githubusercontent.com/66207800/170319584-1eae4fb0-cf42-461e-85b0-cc98829e8b58.png)

**Comment by mjohnsonpint-stripe** [comment]
This is an issue on our end, and we are working to resolve right now. @chaves-stripe and @fkuo-stripe can you update this when fixed?

**Comment by chaves-stripe** [comment]
this is now resolved and 1.8.2 is now properly live and published

**Comment by davidmennie** [comment]
Thank you!
