### ISSUE TITLE
App settings not working in preview mode

### ISSUE THREAD

**Issue by dariodjuric** [stripe/stripe-apps#611]
**Describe the bug**

As of today, we cannot open the app settings in preview mode.  We click the three-dot menu and "Preview app settings", which opens https://dashboard.stripe.com/test/apps/settings-preview in a new tab, but we get the following error:

<img width="666" alt="CleanShot 2022-05-26 at 11 07 34@2x" src="https://user-images.githubusercontent.com/5459296/170456653-f0eb1bf3-566a-4409-b1bf-dac4da115b55.png">

**To Reproduce**

Try opening the app settings in preview mode.

**Expected behavior**

App settings should be opened.

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser: Chrome (latest)

We tried with the following versions of the Stripe CLI and apps plugin:
- 1.8.10 / v1.1.8
- 1.8.11 / v1.1.9

**Comment by ericfrank-stripe** [comment]
Thanks @dariodjuric, we're looking into this issue now.

**Comment by ericfrank-stripe** [comment]
This issue should now be resolved.
