### ISSUE TITLE
Help guide the user [developer] how to test their app in live mode with real data

### ISSUE THREAD

**Issue by cching-stripe** [stripe/stripe-apps#614]
Partner Apps will get reviewed in Live Mode by Stripe with real payments or "customers". Partners would like guidance how to test this or if Stripe can provision this type of data into their accounts.

We currently cannot support seeding data in live mode and therefore should update our docs to inform partners that if they DO want to test in live mode, they should plan on sending a few small charges ($1-$2).

**Comment by auchenberg-stripe** [comment]
We have released External Testing for Apps to make this simpler. Checkout our docs at https://stripe.com/docs/stripe-apps/test-app
