### ISSUE TITLE
Content Security Policy temporarily cached

### ISSUE THREAD

**Issue by rmanzer-stripe** [stripe/stripe-apps#618]
**Describe the bug**
When manually updating the `connect-src` array in `stripe-app.json` to add a new 3rd party URL, the CSP rules appear to be temporarily cached and trigger CSP errors even after restarting the development server

**To Reproduce**
1. Add new URL to `content_security_policy.connect-src` manually
2. Restart dev server
3. Attempt to access URL from Stripe App

**Expected behavior**
I would expect the CSP rules to be updated on server restart and not encounter permission errors.

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1 (21E258)
 - Browser Chrome
 - Version 102.0.5005.61

**Additional context**

**Comment by cchalstrom-stripe** [comment]
@rmanzer-stripe it's currently required to enable to preview again any time the manifest is changed.  This is done by going to https://dashboard.stripe.com/apps/enable-preview while your local dev server is running.  After restarting the dev server, you can press `Enter` to be taken to this page automatically.  This is required to get the new CSP.

**Comment by rmanzer-stripe** [comment]
@cchalstrom-stripe The preview was refreshed several times and this was demonstrated to @tjfontaine-stripe during our Zoom call.

**Comment by cchalstrom-stripe** [comment]
I'm not able to reproduce that behavior.  The connect-src eventually updated for you just by refreshing the dashboard?  For me, that never results in any manifest data being updated.  Restarting the dev server by itself shouldn't be able to change the connect-src, which is what I'm seeing while trying to reproduce this.

**Comment by htheodore-stripe** [comment]
I paired with @rmanzer-stripe and found out that an older version of Stripe Apps CLI was used. This issue has been resolved after upgrading the Stripe apps CLI: `stripe plugin upgrade apps` and re-enabling app preview after change in `stripe-app.json`
