### ISSUE TITLE
App Settings documentation has incorrect URL

### ISSUE THREAD

**Issue by rfelix2121** [stripe/stripe-apps#620]
## Your Problem
On this page: https://stripe.com/docs/stripe-apps/app-settings, there's a link in the **Preview your settings page** section that links to https://dashboard.stripe.com/test/apps/preview-settings 

It should link to https://dashboard.stripe.com/test/apps/settings-preview.

## Existing Documentation URLs (If applicable)
https://stripe.com/docs/stripe-apps/app-settings

**Comment by ange-stripe** [comment]
Thank you! Fix in review now.

**Comment by ange-stripe** [comment]
Should be merged out by eod. Thanks again for the feedback @rfelix2121
