### ISSUE TITLE
LineChart docs page has template code on the page 

### ISSUE THREAD

**Issue by rfelix2121** [stripe/stripe-apps#621]
## Your Problem
On this page: https://stripe.com/docs/stripe-apps/components/linechart, at the very bottom, there's this code. 
`{% partial file=“development/stripe-apps/ui-toolkit/components/partials/component-next-steps.md” /%`

It looks like there's a missing "}" at the end, which would make the page include the markdown partial instead of outputting the code.

## Existing Documentation URLs (If applicable)
https://stripe.com/docs/stripe-apps/components/linechart

**Comment by ange-stripe** [comment]
Thanks for the feedback! fix in place, and should be live by eod.
