### ISSUE TITLE
Trigger app installation from our site

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-apps#626]
We are evaluating how to migrate our Stripe extension into a Stripe app.

It seems that the new app model is very Stripe dashboard centric.

With our extension, Stripe users can trigger the installation/connection directly from our own site. They click our 'Connect' button and we simply redirect them to the [authorization url](https://stripe.com/docs/connect/oauth-reference). If they have multiple stripe accounts, they are prompted by Stripe to choose the correct one. Then they are then redirected to our site.
It makes for a seamless experience.

How can we achieve this flow with the new Stripe app model?

**Comment by auchenberg-stripe** [comment]
Hi @clement911 

Our installation flow for apps supports what we call post install actions, where an app after installation can redirect back to your product/platform. You can leverage this by providing a link to the app listing from within your app, from which your users are redirected back to your product after installation.

Docs: https://stripe.com/docs/stripe-apps/post-install-actions

We are aware that this doesn't give you full parity with an oAuth flow, but it's a start. I'm curious to learn more about how you like an ideal install flow for your app?

**Comment by clement911** [comment]
Thank you @auchenberg-stripe , please see my comment here https://github.com/stripe/stripe-apps/issues/622#issuecomment-1197490372

**Comment by clement911** [comment]
We can make this work with install links.
Closing.
