### ISSUE TITLE
Still not receiving webhook events

### ISSUE THREAD

**Issue by jwright** [stripe/stripe-apps#630]
**Describe the bug**
Our application creates a connected webhook to watch for `customer.created` events on the server using the account's external id for each customer.

```
::Stripe::WebhookEndpoint.create({
  url: url,
  enabled_events: ["customer.created"],
  connect: true
          }, {
            api_key: ENV["STRIPE_API_KEY"],
            stripe_account: stripe_account_id_for_team,
            stripe_version: ENV["STRIPE_API_VERSION"]
          })
```

This does create the webhook successfully as I can see it in the dashboard:

<img width="960" alt="CleanShot 2022-06-02 at 11 49 08@2x" src="https://user-images.githubusercontent.com/35017/171670086-fbb322ef-a132-4fc8-a28c-1275e6041e7c.png">

However, Stripe is not hitting out endpoint when a new customer is created:

<img width="1260" alt="CleanShot 2022-06-02 at 11 49 48@2x" src="https://user-images.githubusercontent.com/35017/171670335-9375f6b1-9ca7-4a15-9294-6b4935c35d88.png">

I do have all the necessary permissions set in the app:

```
"permissions": [
    {
      "permission": "customer_read",
      "purpose": "Allow the app to retrieve customers for use with automation"
    },
    {
      "permission": "event_read",
      "purpose": "Allow the app to get application lifecycle events for use with authorization with our backend"
    },
    {
      "permission": "user_email_read",
      "purpose": "Allow the app to retrieve user emails to use for notifications"
    }
  ],
```

**To Reproduce**
1. Go to Kyber App
2. Create a micro-app with a "customer.created" trigger and a "create a task" action
3. Notice that the webhook was created
4. Create a new customer
5. Notice that a new task is not created
6. Notice that the webhook was not sent the event

**Expected behavior**
We receive the `customer.created` event.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser Chrome
 - Version 101.0.4951.64

**Comment by jwright** [comment]
@mjohnsonpint-stripe Thanks but that is just an issue with the documentation. I exchanged a variable that holds the event. In addition, the webhook is created successfully on the Stripe side.

**Comment by jwright** [comment]
@mjohnsonpint-stripe Any update on this? Not being able to do this is a big deal breaker for our app.

**Comment by chaves-stripe** [comment]
hi @jwright ! I'm an engineer looking into this... could you confirm the account ID of the account with the connected webhook, and if possible, the account ID of the connected account that triggers the customer.created event?

**Comment by jwright** [comment]
@chaves-stripe Hello. Yes, both accounts are the same as I have yet to be able to install it on other accounts. That account is `acct_1BIsRtC4P8wofqAI `.

**Comment by chaves-stripe** [comment]
ah! So a connected webhook endpoint will only receive events/webhooks for events triggered on a connected account, meaning an account that has installed the app. If you just want to test an event firing and your endpoint receiving, you can create a new _direct_ webhook endpoint with the same url as your connected webhook endpoint (to do this, do not check the listen for events on connected accounts checkbox).

**Comment by chaves-stripe** [comment]
@jwright I'm going to close this, but please comment if you have further questions!
