### ISSUE TITLE
Unable to build "Settings cancel catch"

### ISSUE THREAD

**Issue by ppamplona-stripe** [stripe/stripe-apps#631]
Currently in the requirements for Stripe apps we have asked developers to include cancel catch to notify users if they try to navigate away from the page without saving changes.
That implementation is currently not available within our platform, so we will be removing the requirement from the external documentation and will no longer be reviewing it.

[## Existing Documentation URLs (If applicable)](https://stripe.com/docs/stripe-apps/review-requirements#app-settings)

**Comment by mjohnsonpint-stripe** [comment]
This requirement is being removed from app review guidance. @ppamplona-stripe will remove from the documentation. @sandhyaj-stripe will triage the feature request. @mjohnsonpint-stripe will send update in next week's dev comms.
