### ISSUE TITLE
CSV file upload component

### ISSUE THREAD

**Issue by WPaczula** [stripe/stripe-apps#632]
**Is your feature request related to a problem? Please describe.**
I will need to add data in batches and CSV file would make it easy for the team. I didn't find a file upload component in the UI kit though.

**Describe the solution you'd like**
FileInput component that allows to upload a file. CSV is what I'd love the most.

**Describe alternatives you've considered**
Allowing to specify an almost native input with a type="file"

**Comment by mjohnsonpint-stripe** [comment]
This is a duplicate of #196 - @sandhyaj-stripe will take point on prioritization
