### ISSUE TITLE
Inconsistencies for the Works with section between the app listing and app settings page

### ISSUE THREAD

**Issue by jdwilkin4** [stripe/stripe-apps#633]
**Describe the bug**
For some of the apps, there is inconsistent information presented in the Works with section between the app listing and app settings page.

Here is an example:
## App Listing
![Screen Shot 2022-06-02 at 9 56 47 AM](https://user-images.githubusercontent.com/67210629/171683764-ba58ee89-470b-4e12-affe-904dd195e873.png)

## App settings page
![Screen Shot 2022-06-02 at 9 57 15 AM](https://user-images.githubusercontent.com/67210629/171683836-a1235c74-6ec5-442d-a8a8-427552946708.png)

Other apps omit the Works with section completely for the app under the settings page.
For example:

## App listing
![Screen Shot 2022-06-02 at 10 10 06 AM](https://user-images.githubusercontent.com/67210629/171685843-47380966-e735-4a83-968e-bd31fe853282.png)

## App settings page
![Screen Shot 2022-06-02 at 10 11 37 AM](https://user-images.githubusercontent.com/67210629/171686254-da088ad9-41ea-42e8-aed9-7fd3742516aa.png)

Overall, there should be consistency on how the Works with section is presented throughout the app.

**To Reproduce**
Look at the left hand side Works with section in app listing and compare it with Works with section under app settings. Check to see if the information matches. 

**Expected behavior**
For the Works with section to be same in both app listing and app settings

**Comment by ngrubb-stripe** [comment]
Thanks for reporting this @jdwilkin4! We have made the display of this info to be consistent between these two surfaces. 

If a developer utilizes the `stripe.dashboard.drawer.default` viewport, the "Works With" section will now display "All Dashboard pages" on the App Settings page. 

**Example:**
<img width="399" alt="Screen Shot 2022-06-09 at 3 38 17 PM" src="https://user-images.githubusercontent.com/89162925/173378288-a704d60a-0251-431e-ac35-ebea24620f43.png">
