### ISSUE TITLE
Missing links to API docs in Permissions section on app listing

### ISSUE THREAD

**Issue by jdwilkin4** [stripe/stripe-apps#634]
**Describe the bug**
I noticed on one of the apps, there is a missing link to the API docs for one of the Permissions sections in the app listing. 

For example:
![Screen Shot 2022-06-02 at 10 44 01 AM](https://user-images.githubusercontent.com/67210629/171694074-0d93beea-40a6-47be-8186-615f0d1de04d.png)

**Expected behavior**
Consistency in the Permissions section of the app listing to make sure each section has a link to the Stripe API docs.

**Comment by ngrubb-stripe** [comment]
Hey @jdwilkin4 - we agree, a doc link would be helpful here!

This permission does not relate to a Stripe api resource so we don't have a docs page to link to yet. We do plan on adding documentation for this permission in the near future!
