### ISSUE TITLE
oauthContext `undefined` when returning from third-party Login flow for apps bound to non-default viewports

### ISSUE THREAD

**Issue by turnage** [stripe/stripe-apps#637]
**Describe the bug**

For apps bound to e.g. viewport `stripe.dashboard.balance.overview`, the login flow from third-party apps sometimes returns to the default dashboard. It hasn't always done this; not sure if the redirect viewport is nondeterministic or if there was a recent stripe-side change to always land on default dashboard.

Anyway, if it returns to a viewport other than the one the app is bound to, after the user clicks the app tab to switch into the appropriate viewport, the oauth context is lost.

Allowing the app to run in all viewports with `stripe.dashboard.drawer.default` allows it to open on the default dashboard and catch the oauthContext.

**To Reproduce**

1. OAuth2 PKCE flow from an app bound to a viewport
2. On return, find self in default dashboard, click app sidebar button to return to app's bound viewport
3. oauthContext is `undefined`; login can't complete.

**Expected behavior**

On return from PKCE login flow, redirect to the same viewport the user departed from, so user doesn't have to navigate back and so the app can receive oauthContext.

**Screenshots**

**Desktop (please complete the following information):**

NixOS, Firefox 90.

**Comment by turnage** [comment]
Update: I think it may have to do with having multiple tabs of the app open. When I have the app in Stripe Dashboard open in only one tab, I find the expected behavior.

Another strange effect of having the app open in two tabs is: on return from a sign-in flow initiated in the settings page, the user is taken to the default dashboard without oauthContext (so back to the login screen). _This does not occur if only one tab of the app is open._

I repeated this several times and it is deterministic.

**Comment by cchalstrom-stripe** [comment]
Hey, yes this currently won't work if you call `createOAuthState` from tab 1, then afterwards call `createOAuthState` from tab 2, and then finally try to complete the OAuth flow from tab 1.  `createOAuthState` creates a single instance of OAuth state that is required for the OAuth flow to succeed.  Subsequent calls will overwrite prior calls, causing the OAuth flow to fail.  If the oauthContext is undefined and you are taken back to the home page, that means the OAuth was denied, in this case due to an invalid `?state=` value from the query string params.

We will look into options for making this more robust across multiple tabs, though.

**Comment by turnage** [comment]
For communicating between the tabs to share OAuth state, what would you recommend? Because I must have createOAuthState's returned values to create the `Button`'s href property, I want the info before rendering the `Button`.

Perhaps I could share them by broadcast channels or some other means, but I don't want to introduce inter-tab communication if not necessary.

Forgive me if there's a simple method I'm not seeing like generating the login link on click.

**Comment by cchalstrom-stripe** [comment]
I think one thing we could do is just return you the existing OAuth state, if one was already created previously.  We don't currently support broadcast channels or listening to `storage` events on the dashboard.

**Comment by cchalstrom-stripe** [comment]
This should be fixed now.
