### ISSUE TITLE
Caution type banner displays wrong icon

### ISSUE THREAD

**Issue by jcipriano-stripe** [stripe/stripe-apps#638]
**Describe the bug**
When implementing a banner with `type="caution"` the wrong icon is displayed. It should be the "i" instead of "!".

**To Reproduce**
1. Creat an app.
2. Add the banner component with `type="caution"`.
3. Open preview.

**Expected behavior**
A described in the [docs](https://stripe.com/docs/stripe-apps/components/banner), the icon should be an "i" with yellow background.

**Screenshots**
![Screen Shot 2022-06-03 at 4 45 50 PM](https://user-images.githubusercontent.com/97692445/171967486-4695589f-6bac-445a-b0e6-ccf010739780.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 102.0.5005.61

**Comment by jasontang-stripe** [comment]
Hi @jcipriano-stripe The exclamation mark “!" is the correct icon for "caution". "i" is information for tooltip usage.

**Comment by ericfrank-stripe** [comment]
The docs site is on an older version. I'm updating it to resolve the discrepancy.

**Comment by ericfrank-stripe** [comment]
The docs site has been updated to reflect the new icon.
