### ISSUE TITLE
ContextView footerContent component triggers an error when passing a nested Button component in a Banner actions property

### ISSUE THREAD

**Issue by bcomerford** [stripe/stripe-apps#641]
**Describe the bug**
[The documentation](https://stripe.com/docs/stripe-apps/components/contextview) specifies that the `ContextView` component accepts a `footerContent` prop and a `banner` prop, as a ReactNode type where I am rendering a `Banner` conditionally. However, when passing a `Button` inside the banner's `actions` property it, the drawer breaks with the following error:

```Objects are not valid as a React child (found: object with keys {id, kind, children}). If you meant to render a collection of children, use an array instead.```

Wrapping in `Box` doesn't work either, removing the actions property from the banner allows it to render properly though. Rendering the banner without the conditional also works.

**To Reproduce**
1. Create a banner with a button in the `actions` property
2. Have it render conditionally from a boolean state with `false` as default
3. Set the state to `true` via a toggle button or `useEffect`

**Expected behavior**
Banner with button in actions should still render

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 102

**Additional context**

**Comment by ericfrank-stripe** [comment]
Workaround (or at least a data point): The above code works if you add a `key` to `ContextView` that changes based on the banner state:
```
<ContextView
  key={hasBanner ? 0 : 1}
```

**Comment by dannygarcia-stripe** [comment]
The fix has made it into the dashboard. I was able to confirm the repro example now works! @bcomerford feel free to reopen if the issue is still occurring.
