### ISSUE TITLE
Timeline Component

### ISSUE THREAD

**Issue by rmanzer-stripe** [stripe/stripe-apps#645]
**Is your feature request related to a problem? Please describe.**
I would appreciate a component to display a chronological series of events with including data

**Describe the solution you'd like**
A component (2 actually) that allows a developer to create a Timeline and Timeline items. 

**Describe alternatives you've considered**
* Tables 😝
* List 😦

**Additional context**
I was thinking something closer to this Vue component: https://vuetifyjs.com/en/components/timelines/

**Comment by ericfrank-stripe** [comment]
Hey @rmanzer-stripe, we have an existing issue for this. Consolidating feedback here: https://github.com/stripe/stripe-apps/issues/202
