### ISSUE TITLE
Elements rendered incorrectly and out of order

### ISSUE THREAD

**Issue by zemaj** [stripe/stripe-apps#648]
**Describe the bug**
When state is changed on a rendered view so that a new component is added or removed, the newly rendered view has elements appearing out of order or duplicated.

**To Reproduce**
Create a view with the following code;
```
const DefaultView = ({ userContext, environment }: any) => {
  const [clicked, setIsClicked] = useState(false);

  return (
    <ContextView title="Example">
      <Box>Line 1</Box>
      { clicked && <Box>Line 2</Box> }
      <Box>Line 3</Box>
      <Button onPress={() => setIsClicked(!clicked)} type="primary">Click</Button>
    </ContextView>
  );
};

export default DefaultView;
```

**Expected behavior**
After clicking the button 1 time, expect to see in order:
```
Line 1
Line 2
Line 3
```
Instead seeing screenshots below:

**Screenshots**
0 clicks:
<img width="330" alt="Screen Shot 2022-06-14 at 3 17 11 pm" src="https://user-images.githubusercontent.com/28863/173498834-434fcffb-1dc1-45ff-8930-8537cae00980.png">

1 click:
<img width="333" alt="Screen Shot 2022-06-14 at 3 17 29 pm" src="https://user-images.githubusercontent.com/28863/173498852-d30d5281-2879-4961-b0f5-7edc05c96794.png">

2 clicks:
<img width="335" alt="Screen Shot 2022-06-14 at 3 17 54 pm" src="https://user-images.githubusercontent.com/28863/173498908-c81bb856-7a0b-4cc0-a531-015be90abda7.png">

3 clicks:
<img width="336" alt="Screen Shot 2022-06-14 at 3 18 29 pm" src="https://user-images.githubusercontent.com/28863/173498978-6eec9792-f03c-4599-89aa-23c0026a5aa9.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 102.0.5005.115

**Additional context**
Occurs when testing using `stripe apps start` command. 
Updated to version 9.8.0 of [stripe-node](https://github.com/stripe/stripe-node) today. Can not confirm if issue was occuring before upgrade or not.

**Comment by ericfrank-stripe** [comment]
We've isolated the root cause and are working on deploying a fix.
