### ISSUE TITLE
More permissions required for application (Stripe Elements)

### ISSUE THREAD

**Issue by tiinanguyen** [stripe/stripe-apps#650]
We're using Stripe's JS SDK and it relies on the permissions we set in our app since we are migrating away from our current Connect Extension. We are running into an issue where the Stripe API call generated by the SDK when trying to build up the Elements UI is erroring out with the new permissions. 

Request generated by SDK:
```
GET https://api.stripe.com/v1/elements/sessions?key=[...]&_stripe_account=[...]&type=setup_intent&locale=en&client_secret=[...]&expand[0]=payment_method_preference.setup_intent.payment_method
```
Response:
```
{
  "error": {
    "code": "more_permissions_required_for_application",
    "message": "This application does not have the required permissions for this endpoint on account ‘…’. Having the 'read_only' scope would allow this request to continue.",
    "type": "invalid_request_error"
  }
}
```

We are currently testing with the following permissions:
- customer_read + customer_write
- setup_intent_read + setup_intent_write
- invoice_read
- subscription_read + subscription_write
- payment_intent_read + payment_intent_write
- payment_method_read + payment_method_write
- plan_read + plan_write
- product_read
- checkout_session_read
- charge_read
- event_read
- balance_read
- tax_rate_read
- user_email_read
- source_read + source_write

What [permissions](https://stripe.com/docs/security/permissions) would we need to get the above request to work?

**Comment by chaves-stripe** [comment]
hi @tiinanguyen! I have a follow up question to help us debug this issue. [What type of API key](https://stripe.com/docs/keys#obtain-api-keys) are you using when making this request?

**Comment by chaves-stripe** [comment]
hi @tiinanguyen, you can disregard the last question. We were able to reproduce and are working on next steps on our end. Thanks for your patience

**Comment by tiinanguyen** [comment]
Hi @chaves-stripe Checking in if there's any updates here?

**Comment by chaves-stripe** [comment]
hi @tiinanguyen we have fully identified the problem and are working on a fix. I anticipate a fix landing early next week

**Comment by chaves-stripe** [comment]
This can be resolved by adding the `elements_write` permission
