### ISSUE TITLE
Pressing the X button on a FocusView with confirmCloseMessages does not show the confirm close dialog

### ISSUE THREAD

**Issue by ericfrank-stripe** [stripe/stripe-apps#651]
**Describe the bug**
The confirmation dialog does not show up on closing the focussed view by clicking the X at the top or when we have a secondary action like cancel. It works only when focussed view is closed by clicking outside or pressing escape.

**To Reproduce**

Using this app:
```
import {useState} from 'react';
import {
  Button,
  ContextView,
  FocusView,
} from '@stripe/ui-extension-sdk/ui';

const App = () => {
  const [shown, setIsShown] = useState(true);

  return (
    <ContextView title="Test">
      <FocusView
        title="Test"
        shown={shown}
        onClose={() => setIsShown(false)}
        confirmCloseMessages={{
          title: "Are you sure you want to exit?",
          description: "You may lose data.",
          cancelAction: "Cancel",
          exitAction: "Exit",
        }}
        secondaryAction={<Button onPress={() => setIsShown(false)}>Close</Button>}
      >
        Hello
      </FocusView>
    </ContextView>
  );
};

export default App;
```

Click either the "X" button at the top of the FocusView or the "Close" button at the bottom. The close confirmation dialog is not displayed in either case.

**Expected behavior**
The close confirmation dialog is displayed

**Comment by sandhyaj-stripe** [comment]
From Discord  + internal user reported.

**Comment by mangatinanda** [comment]
Any update on this? @ericfrank-stripe

**Comment by ericfrank-stripe** [comment]
@mangatinanda Engineers are working on this issue and we'll leave an update here when it's resolved.

**Comment by ericfrank-stripe** [comment]
This issue has been resolved.

**Comment by mangatinanda** [comment]
@ericfrank-stripe do we need to upgrade the SDK to get this fix? 

I have tested this in our test account. The confirmation dialog is show on clicking cancel/close icon but the actions in the confirmation are not working properly. Feels very buggy.

**Comment by ericfrank-stripe** [comment]
@mangatinanda No SDK upgrade is needed. A screen recording would help, but the most helpful thing would be a code sample that we can run locally to reproduce what you're seeing. Thanks for your help.

**Comment by mangatinanda** [comment]
Uploading stripe-focus-view.mov…

I was able to reproduce this with the test code in the issue description itself. Please check the recording. When clicked on secondary action and then on the cancel button in the confirmation dialog, the UI just flashes. Please also test this along with #656 issue once.

**Comment by ericfrank-stripe** [comment]
@mangatinanda Thanks, I can reproduce this on my end. We'll work on a fix.

**Comment by ericfrank-stripe** [comment]
@mangatinanda We've isolated the issue and are deploying a partial fix soon. To summarize the issue:

- When an app chooses to close itself by setting `shown` to `false`, we cannot display the close confirmation dialog because if the user chooses not to close the dialog, we have no way of setting `shown` back to `true`
- For this reason, the fix that we're deploying today makes it so that clicking an app-provided button that sets `shown` to `false` closes `FocusView` without showing the dialog
- The fix for the "X" button remains in place (it will still show the confirmation dialog)
- We are now working on an update to the SDK that will allow developers to pass an `onOpen` function (or similar) to `FocusView` that will enable the close confirmation modal to work with app-provided buttons:

```
<FocusView
  title="Test"
  shown={shown}
  onOpen={() => setIsShown(true)}
  onClose={() => setIsShown(false)}
  confirmCloseMessages={{
    title: "Are you sure you want to exit?",
    description: "You may lose data.",
    cancelAction: "Cancel",
    exitAction: "Exit",
  }}
  secondaryAction={<Button onPress={() => setIsShown(false)}>Close</Button>}
>
```

I will update this ticket when the new SDK has been released.

**Comment by ericfrank-stripe** [comment]
The partial fix described above has been deployed.

**Comment by jackokerman-stripe** [comment]
@mangatinanda we added a new `setShown()` prop in the latest version of `@stripe/ui-extension-sdk` that allows the close confirmation to work as expected in every close scenario. See the [updated `FocsuView` docs](https://stripe.com/docs/stripe-apps/components/focusview) for full information and a detailed example using the new prop.
