### ISSUE TITLE
Permissions issue with /setup/intents/confirm

### ISSUE THREAD

**Issue by rfelix2121** [stripe/stripe-apps#659]
**Describe the bug**
Our customers use our payment pages to update their billing information within Stripe. This works great using Stripe Connect currently, but after our Stripe app is installed, we get switched to the new Apps permission model and can no longer save cards. 

Specifically, this seems to be a problem with the /setup_intents/confirm endpoint.

The error we're seeing is

```
{
   "error":{
      "code":"more_permissions_required_for_application",
      "message":"This application does not hae the required permissions for this endpoint on account 'xxxxxxxxxxxxxxx'. Having the 'read_write' scope would allow this request to continue.",
      "type":"invalid_request_error"
   }
}
```

We are currently testing with the following permissions:

- customer_read + customer_write
- setup_intent_read + setup_intent_write
- invoice_read + invoice_write
- subscription_read + subscription_write
- payment_intent_read + payment_intent_write
- payment_method_read + payment_method_write
- apple_pay_domain_read + apple_pay_domain_write
- coupon_read + coupon_write
- mandate_read + mandate_write
- token_read + token_write
- webhook_read
- connected_account_read
- plan_read
- product_read
- charge_read
- event_read
- source_read + source_write

What permissions do we need to get this working?

**Comment by rfelix2121** [comment]
@jcipriano-stripe Looking at my git repo, setup_intent_read + setup_intent_write have been in there since May 3rd. So it definitely isn't something that I added recently.

**Comment by chaves-stripe** [comment]
@rfelix2121 to help me debug a bit here, could you give account Id of an account that has installed this app where you are seeing this error? Thanks!

**Comment by rfelix2121** [comment]
I'm pretty sure I saw it last in acct_1KwBT0GOXV6shsJK. Thanks!

**Comment by jcipriano-stripe** [comment]
Related to [issue 650](https://github.com/stripe/stripe-apps/issues/650)

**Comment by chaves-stripe** [comment]
This can be resolved by adding the `elements_write` permission
