### ISSUE TITLE
No way to use Stripe Elements

### ISSUE THREAD

**Issue by ChargeAutomation** [stripe/stripe-apps#660]
**Describe the bug**
With Connect Extension oAuth https://stripe.com/docs/connect/oauth-reference#post-token-request,  we were able to retrieve stripe_publishable_key that we can use to create Stripe element on our frontend application.

Is it not possible to do same for clients who has installed Stripe app? Is it possible to get publishable key of client, who has installed our Stripe App?

**To Reproduce**
1. Publish app from same account on which you have Connect Extension.
2. Once a client installed your app (who is already connected with you through Connect Extension oAuth), old publishable_key will get removed.
3. Then Stripe Card Element start showing message that "pk_test_****** key is expired".
4. https://stripe.com/docs/payments/accept-card-payments?platform=web&ui=elements we are unable to use this card element for our clients who has installed our app, because this element needs publishable_key of that client and there is no way to get the publishable_key through API. The only way is, client needs to copy publishable_key from Stripe dashboard and then manually put it on our platform.

**Additional context**
This is not only just for Connect Extension account, this issue is for new Stripe App users as well, because there is no way that they can use Stripe Elements.

**Comment by jcipriano-stripe** [comment]
Closing this ticket and will be tracking in [650](https://github.com/stripe/stripe-apps/issues/650).
