### ISSUE TITLE
Renderer crashing when a list item's child swaps to a child that is the same named component

### ISSUE THREAD

**Issue by TapaiBalazs** [stripe/stripe-apps#661]
**Describe the bug**
When a list item's child swaps to a child that is the same named component with the same property types (in our example it is Box components with css props, even though the css is different) the renderer throws an error and the app crashes.

**To Reproduce**
```
import { Box, ContextView } from '@stripe/ui-extension-sdk/ui';
import { useEffect, useState } from 'react';

const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

const NowYouSeeMe = () => {
  const [loading, setLoading] = useState('idle');

  useEffect(() => {
    setLoading('loading')
    setTimeout(() => setLoading('loaded'), 5000); // simulating a trigger which re-renders the component
  });
  return loading === 'loaded' ? (
    <Box css={{
      background: 'container',
      padding: 'small',
    }}>Now you see me.</Box>
  ) : (
    <Box css={{
      background: 'container',
      padding: 'small',
      layout: 'column',
      borderRadius: 'small',
      font: 'caption',
    }}>Now you don't!</Box>
  )
}

const DefaultView = () => {
  return (
    <ContextView title="Minimal bug reproduction example">
      {
        arr.map((id: number) => <NowYouSeeMe key={id}/>)
      }
    </ContextView>
  );
}

export default DefaultView;
```

**Expected behavior**
After 5 seconds you should see a list of Box components containing "now you don't"

**Screenshots**
We are reluctant to share proprietary app video, we can provide a video to you using private channels.

**Desktop (please complete the following information):**

**Additional context**
see related issue: https://github.com/stripe/stripe-apps/issues/606

 The component that is replicated in the list has a key property, but its contents are not separately keyed. If we key the contents of the children then the error does not occur.

**Comment by ericfrank-stripe** [comment]
This issue has been resolved. No SDK updates required.

**Comment by ericfrank-stripe** [comment]
Unfortunately we've had to roll back because a new issue was introduced: https://github.com/stripe/stripe-apps/issues/669

I'll post here with updates as we work on a fix.

**Comment by ericfrank-stripe** [comment]
Rolled forward.
