### ISSUE TITLE
Stripe Apps CLI prompt messages not showing up on Windows' git bash

### ISSUE THREAD

**Issue by htheodore-stripe** [stripe/stripe-apps#663]
**Describe the bug**
Stripe Apps CLI prompt messages not showing up on Windows' git bash

**To Reproduce**
1. Run `stripe apps create helloworld` on git bash windows
2. Prompt message not showing up

**Expected behavior**
Prompt message should be shown

**Screenshots**

**CLI (please complete the following information):**
 - Stripe CLI: 1.8.11
 - Apps plugin: 1.2.4

**Additional context**

**Comment by htheodore-stripe** [comment]
Issue on stripe-cli for more context: https://github.com/stripe/stripe-cli/issues/890

**Comment by gabrielhurley-stripe** [comment]
Closing as a dupe of https://github.com/stripe/stripe-cli/issues/890 which has more investigation and context.
