### ISSUE TITLE
Stripe Signature header key not matching documentation

### ISSUE THREAD

**Issue by rmanzer-stripe** [stripe/stripe-apps#667]
**Describe the bug**
The key that identifies the Stripe Signature header in requests originating from my Stripe App doesn't match 
the value specified in Server Side logic doc

**To Reproduce**
1. Check code snippet in [Server side logic](https://stripe.com/docs/stripe-apps/build-backend) doc 
2. Trigger request to external server
3. Examine Header values in request to external server

**Expected behavior**
I would expect the header keys to match the values provided in the docs.  At the least this failure can cause all requests to appear unverified.  Where code relies on the key as an index for header retrieval this can cause the external server to crash.

**Screenshot
![Screen Shot 2022-06-29 at 2 39 35 PM](https://user-images.githubusercontent.com/93411628/176549947-6d536499-5390-4306-aabf-e22290fdd5e5.png)
s**

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Browser Chrome
 - Version 103.0.5060.53

**Comment by ericfrank-stripe** [comment]
Hi @rmanzer-stripe, is this a request that you're initiating from your app to your backend? Something like this?

```
return fetch(`https://example.com/${endpoint}/`, {
      method: 'POST',
      headers: {
        'Stripe-Signature': await fetchStripeSignature(),
        'Content-Type': 'application/json',
      },
```

If so, can you double check the spelling of `Stripe-Signature` in your code? If not, can you help me understand where the misspelled `Stripe-Sgnature` is coming from?

**Comment by rmanzer-stripe** [comment]
:facepalm:
