### ISSUE TITLE
Support border-radius on Img component

### ISSUE THREAD

**Issue by jackokerman-stripe** [stripe/stripe-apps#668]
**Is your feature request related to a problem? Please describe.**
Someone asked if it was possible to set the `border-radius` property on an `Img` component. 

**Describe the solution you'd like**
A way to set the `border-radius` directly on the `Img` component. Some possible options for this are:
1. Provide a `borderRadius` prop directly on the `Img` for setting the CSS property of the `<img>` tag. This would be the quick and easy way to do it.
```tsx
<Img
  src={src}
  height="40"
  width="40"
  alt={alt}
  borderRadius="medium"
/>
```
2. Provide a `css` property and allow a CSS object that permits certain styles to be applied to the image. This is consistent with what we're doing with `Box` and `Inline`, and would be more flexible if we ever wanted to add additional styling properties.
```tsx
<Img
  src={src}
  height="40"
  width="40"
  alt={alt}
  css={{
    borderRadius: "medium",
  }}
/>
```
**Describe alternatives you've considered**
We don't have any official guidance on this, however adding a border radius can can be achieved by wrapping the `Img` in a `Box`: 
```tsx
<Box
  css={{
    borderRadius: "large",
    overflow: "hidden",
    width: "fit",
    display: "grid",
  }}
>
  <Img src={...} />
</Box>
```
This achieves the desired effect, but adds an extra wrapper `<div>`. We also don't have this documented, and we'd probably want a more seamless solution if it was something we'd want to support officially.

**Comment by cching-stripe** [comment]
Thanks @jackokerman-stripe! Triaged to UIXT.

**Comment by jackokerman-stripe** [comment]
The docs have been updated with an example of how to [add rounded corners to an `Img` component](https://stripe.com/docs/stripe-apps/components/img#rounded-corners).
