### ISSUE TITLE
Can't align spinner to center of FocusView

### ISSUE THREAD

**Issue by omerfranco** [stripe/stripe-apps#671]
We have loading spinner that was aligned to center of FocusView.
Looks like something in the FocusView layout was changed and the spinner can't be aligned to center any more (The height of the main element inside FocusView is not 100%). 
In ContextView it's working good.
<img width="565" alt="image" src="https://user-images.githubusercontent.com/95418669/177039672-9ad35e17-09cf-44f4-9338-9b7d272c434f.png">

**Comment by dannygarcia-stripe** [comment]
@omerfranco this should now be possible. The FocusView content container flexbox styles match that of ContextView. Please reopen if you're continuing to have trouble!
