### ISSUE TITLE
Stripe type doesn't have `apps` property 

### ISSUE THREAD

**Issue by WPaczula** [stripe/stripe-apps#672]
**Describe the bug**
I followed the docs from here: https://stripe.com/docs/stripe-apps/store-secrets#set-a-secret to store a secret

```
import { createHttpClient, STRIPE_API_KEY } from '@stripe/ui-extension-sdk/http_client';
import Stripe from 'stripe';

const stripe: Stripe = new Stripe(STRIPE_API_KEY, {
  httpClient: createHttpClient() as Stripe.HttpClient,
  apiVersion: '2020-08-27',
});

...

 stripe.apps.secrets.create({
    scope: { type: 'user', user: userId },
    name: 'token',
    payload: token
  })

```

Error that I get is:
`property 'apps' does not exist on type 'Stripe'`

My packages versions. I tried to update them to the latest:
"@stripe/ui-extension-sdk": "^8.1.0",
"stripe": "^9.11.0"

**To Reproduce**
1. Create a stripe app
2. Try to store a secret

**Expected behavior**
TS allows me to use stripe.apps.secrets and helps me with typing

**Desktop (please complete the following information):**
 - OS Windows
 - Browser n/a
 - Version n/a

**Comment by WPaczula** [comment]
I found out that this may be happening because the type comes from `@stripe/ui-extension-sdk` for some reason which has a dep on `stripe^8.174.0`. This version doesn't have apps property as it was added in [v9.3.0](https://github.com/stripe/stripe-node/releases/tag/v9.3.0)

**Comment by ericfrank-stripe** [comment]
@WPaczula Can you try using NPM's `overrides` feature to lock your version to the one you have installed?

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

```
// package.json

{
  "overrides": {
    "stripe": "<YOUR_VERSION>"
  }
}
```

Let me know if that works. We're still working on a fix on our end and will be updating the `stripe` version in the SDK.

**Comment by ericfrank-stripe** [comment]
The version of `stripe` in the dependencies of the latest SDK `8.2.0` has been updated one that includes the `apps` property. We're looking into making it a peer dependency to prevent similar issues in the future.
