### ISSUE TITLE
Stripe App doesn't load after upload/install process without local server running

### ISSUE THREAD

**Issue by geraldkarmen** [stripe/stripe-apps#674]
**Describe the bug**
After uploading and installing in private a new version of my app, i cannot get it load through stripe dashboard without keeping my `stripe apps start` process running

**To Reproduce**
1. set new version of the app
2. upload & install this new version 
3. switch test mode to "off" so that my app environment.mode === `live`
4. cut off my local stripe app server (`stripe apps start`)
5. refresh the dashboard 

**Expected behavior**
The App running as the same as when i'm running it with `stripe apps start` 

**Screenshots**
![Capture d’écran 2022-07-08 à 13 29 00](https://user-images.githubusercontent.com/107848488/177983941-20e98ef5-58e6-4a6b-b1ee-3248a6f797a1.png)
![Capture d’écran 2022-07-08 à 09 30 12](https://user-images.githubusercontent.com/107848488/177983950-30f3a21e-0c7a-4535-9b47-58da911af35b.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.4
 - Browser: Chrome
 - Version: 103.0.5060.114 

**Additional context**

**Comment by ericfrank-stripe** [comment]
@geraldkarmen It looks like you still have app preview mode enabled. Exiting your local server doesn't exit preview mode in the dashboard. To exit preview mode, click the three-dot menu in the upper right side of the drawer and click "Turn off app preview."

<img width="207" alt="Screen Shot 2022-07-08 at 9 23 00 AM" src="https://user-images.githubusercontent.com/93341286/178011438-f0f9f0f9-1677-4b17-956e-dba5496ae4a7.png">

The error message in the drawer isn't very helpful here, and we're working on improving it.

I'm closing this issue for now, but please leave a comment if you have any further questions.
