### ISSUE TITLE
Stripe Extension stopped working after clients install the Stripe App

### ISSUE THREAD

**Issue by wilson-martins** [stripe/stripe-apps#678]
**Describe the bug**
We are facing some issues with our Stripe Extension now that the Stripe App has launched.
We are seeing our Stripe Extension breaking for our clients that install the Stripe App, specially the Recipients integration:

com.stripe.exception.PermissionException: This application does not have the required permissions for this endpoint on account 'acct_******'. Having the 'read_only' scope would allow this request to continue.; code: more_permissions_required_for_application; request-id: req_******

After the client detaches and reconnects the extension, it seems to be working properly again. But that does not seem to be the right solution. Is there any permission required for us to add to the Stripe App to allow for the recipient connection? Or is there any other solution that we are missing?

The Recipients entity seems to be deprecated, is there support for it in the new permission model?

**To Reproduce**
1. Connect a client account with Stripe Extension
2. Make sure that the integration is working
3. Install the Stripe App: integration will stop working for the Recipients entity
4. Detach and reconnect Stripe Extension, integration should work again

**Expected behavior**
Stripe Extension continues to work after clients install the Stripe app

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 103

**Comment by charlesw-stripe** [comment]
This issue has been resolved.
