### ISSUE TITLE
Text Alignment issues for buttons

### ISSUE THREAD

**Issue by jdwilkin4** [stripe/stripe-apps#693]
**Describe the bug**
We have noticed that a couple of the apps have some text alignment issues inside the buttons. For some of the buttons, the text has moved to the upper left hand corner of the button and is no longer aligned in the center. 

**Expected behavior**
Button text should be aligned in the center. 

**Screenshots**

**Desktop (please complete the following information):**

**Comment by ericfrank-stripe** [comment]
Hi @jdwilkin4, I'm working on reproducing the bug, and so far the full-width centered [example in our docs](https://stripe.com/docs/stripe-apps/components/button#full-width-buttons) is working:
```
<Button type="primary" css={{width: 'fill', alignX: 'center'}}>
  Full-width button
</Button>
```

I've tried various permutations including adding an icon. Can you provide a minimal code sample showing the bug to help us narrow this down? Thanks.

**Comment by jdwilkin4** [comment]
Here is the code example for the login button

```
import { Box, Icon } from '@stripe/ui-extension-sdk/ui';
import React from 'react';

export const LabelWithIcon: React.FC<{
  icon: string;
  iconPosition?: 'left' | 'right';
  children: string | string[];
}> = ({ icon, children, iconPosition = 'left' }) => {
  return (
    <Box css={{ layout: 'row', alignY: 'center' }}>
      {iconPosition === 'right' && <>{children}&nbsp;</>}
      <Icon size="xsmall" name={icon} />
      {iconPosition === 'left' && <>&nbsp;{children}</>}
    </Box>
  );
};
```
When I add `alignX: 'center'` to `<Box css={{ layout: 'row', alignY: 'center' }}>` then it works. 
But the issue we are facing is that it was centered before without having to add the `alignX: 'center'`

**Comment by ericfrank-stripe** [comment]
@jdwilkin4 Thanks, I'm able to repro now. I'll post here after we've investigated further.

**Comment by ericfrank-stripe** [comment]
We've discovered the root cause. A recent update to our design framework is causing `alignX` and `alignY` values to stop cascading. We're working on a fix, and I'll update this issue when it has been deployed.

**Comment by ericfrank-stripe** [comment]
This issue has been resolved. All alignment should work as it did before.
