### ISSUE TITLE
Non-admin users get an error for Featured Apps when opening the + drawer menu 

### ISSUE THREAD

**Issue by efouts** [stripe/stripe-apps#695]
**Describe the bug**
Non-admin dashboard users get an error for Featured Apps when opening the + drawer menu 

**To Reproduce**
1. Go to Stripe dashboard as a user with a non-admin role such as support specialist
2. Click on '+' in the Stripe apps drawer
3. See error icon under Featured Apps in the drawer pop out

**Expected behavior**
Expecting featured apps list to be displayed. Each featured app will take the user to the marketplace when clicked.

**Screenshots**

![image (2)](https://user-images.githubusercontent.com/1428145/180814707-e7ee3430-e386-4b4f-8878-5ca62d3483a7.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Browser: Chrome
 - Version: 103

**Comment by kweng-stripe** [comment]
Fixed
