### ISSUE TITLE
Not able to find the event "account.application.authorized"

### ISSUE THREAD

**Issue by PhilipAnd** [stripe/stripe-apps#697]
## Your Problem
In the documentation it states that there is the following event for when a user installs the app "account.application.authorized". 

However when trying to find it in the Stripe dashboard to add it, it cannot be found:
![Events](https://user-images.githubusercontent.com/963460/181724698-a549452d-e020-4cf1-82e6-da3c57c87ed6.jpg)

## Existing Documentation URLs (If applicable)
https://stripe.com/docs/stripe-apps/build-backend#stripe-apps-events

**Comment by fkuo-stripe** [comment]
Hi @PhilipAnd, the event will show up in that dialog once you've selected "Public to all Stripe users" as the distribution type for one of your apps. Please join the waitlist to be notified when public distribution is available!

**Comment by PhilipAnd** [comment]
Thanks @fkuo-stripe

**Comment by fkuo-stripe** [comment]
Related #184
