### ISSUE TITLE
Access React component programmatically

### ISSUE THREAD

**Issue by dimitrisraptis96** [stripe/stripe-apps#698]
Any way to access a React component programmatically?

I've tried to both pass a ref to the `Box` component and get the HTML element with the 'traditional' `document.getElementById('box')` but neither of these solutions seems to work.

Any suggestion?

```javascript
const App = ({ userContext, environment }: ExtensionContextValue) => {
  const ref = React.useRef();

  React.useEffect(() => {
    console.log(ref.current);
  }, [ref]);

  React.useLayoutEffect(() => {
    console.log(document.getElementById("box"));
  }, [ref]);

  return (
    <ContextView title="BrandBird" brandColor="#1DA1F1">
      <Box id="box" ref={ref}>
        Hi
      </Box>
    </ContextView>
  );
};
```

**Comment by ericfrank-stripe** [comment]
Hi @dimitrisraptis96, for security purposes, Stripe Apps do not have direct access to the DOM, so `ref`s and `document` won't work. You can read more about the limitations of our sandbox here: https://stripe.com/docs/stripe-apps/how-ui-extensions-work#sandbox-limitations
