### ISSUE TITLE
Cannot get name of element 

### ISSUE THREAD

**Issue by PhilipAnd** [stripe/stripe-apps#705]
**Describe the bug**
I would like to get the name of a form item when the onChange event fires on said element. However, when trying the code below it seems to return undefined. Is there a different way to get the element name through the event?

**To Reproduce**
```
<Select
  name="love-pets-001"
  label="Choose a pet"
  onChange={(e) => {
    console.log(e.target.name); // returns undefined
  }}
>
  <option value="">Choose an option</option>
  <option value="dogs">Dogs</option>
  <option value="cats">Cats</option>
</Select>
```

**Comment by PhilipAnd** [comment]
It seems like for the DateField component there is also missing some data in the event. 

The following code: 
`<DateField name="test" label="test" id="5" onChange={(e) => console.log(e)} />`

Produces the following result:

`{
  "target": {
    "value": "2020-02-02"
  }
}`

In this case e.g. the Id isn't present. The example is that if you build dynamic forms, then you would need the ID for the element.

**Comment by ericfrank-stripe** [comment]
The `name` property is now passed in the `event.target` for all inputs except `DateField`. No SDK update needed.

`DateField` is a different fix because it's a composite element, so I opened up a new ticket: https://github.com/stripe/stripe-apps/issues/710
