### ISSUE TITLE
cannot fetch backend_signature

### ISSUE THREAD

**Issue by segalee17** [stripe/stripe-apps#706]
**Describe the bug**
Failed to fetch data backend_signature, request gets 403 error (fundbox.dashboard.3)

**Expected behavior**
Review and draw funds button 
**Screenshots**
<img width="1787" alt="Screen Shot 2022-08-07 at 18 40 03" src="https://user-images.githubusercontent.com/107105504/183299118-705db50a-c753-4a56-88bc-46212ca0e2ec.png">

**Comment by gabrielhurley-stripe** [comment]
This was an issue on our end and should be remediated now. Thanks for opening this issue and apologies for the confusion.
