### ISSUE TITLE
Cannot update the defaultValue of TextField

### ISSUE THREAD

**Issue by PhilipAnd** [stripe/stripe-apps#712]
**Describe the bug**
If you try and update the defaultValue of a textField through the state it doesn't update.

**To Reproduce**
```
       const [customButtonText, setCustomButtonText] = React.useState('initial text');

      <TextField defaultValue={customButtonText} />
      <Inline>{customButtonText}</Inline>
      <Button onPress={() => setCustomButtonText('Text Is Updated') }>
          Click
      </Button>
```

**Expected behavior**
In the case above both the <Inline> and <TextField> should have the text set to "Text is Updated", however, only the <Inline> text gets updated, not the value of the textField.

**Comment by ericfrank-stripe** [comment]
Hi @PhilipAnd, the `defaultValue` prop in React only sets the value of an input when it's first mounted. See:

https://reactjs.org/docs/uncontrolled-components.html#default-values

To force an input to re-mount, the easiest way is to update its `key`. I've seen a number of apps use the `defaultValue` as the `key` to achieve the effect you're looking for:

```jsx
const [customButtonText, setCustomButtonText] = React.useState('initial text');

<TextField defaultValue={customButtonText} key={customButtonText} />
<Inline>{customButtonText}</Inline>
<Button onPress={() => setCustomButtonText('Text Is Updated') }>
  Click
</Button>
```

I'll close this for now, but let me know if this approach works for you. It's definitely something we (Stripe) will consider documenting.

**Comment by PhilipAnd** [comment]
Thank you very much - I apologize for assuming this was a bug in the Stripe framework.

**Comment by ericfrank-stripe** [comment]
@PhilipAnd No problem at all. Using uncontrolled inputs (as we recommend) is not always familiar to a lot of React developers, myself included.

**Comment by PhilipAnd** [comment]
The only disadvantage with updating the key is that the field loses focus on each key press :)
