### ISSUE TITLE
User unable to call fetchStripeSignature() when signed in with a Custom User Role. 

### ISSUE THREAD

**Issue by ericlackey** [stripe/stripe-apps#713]
**Describe the bug**
Stripe Dashboard users are unable to call the fetchStripeSignature() method when signed in with Custom User Role. These users are also using SSO, but we have other users that use SSO and standard roles (such as view-only) and they work fine. The error we see in the console is:

An error occurred trying to retrieve Stripe Signature: Error: You do not have the required permissions for this endpoint on account 'acct_zzzzzzzz'. Having more permissions would allow this request to continue.

**To Reproduce**
1. Sign in as a Stripe Dashboard user using a Custom Role.
2. Attempt to use a Stripe App that calls the fetchStripeSignature() method.

**Expected behavior**
A Stripe Signature is returned.

**Desktop (please complete the following information):**
 - Mac OS 12.4
 - Chrome
 - Version 104.0.5112.79

**Comment by htheodore-stripe** [comment]
Hi Eric! Thanks for reporting this.

@fkuo-stripe, is this an expected behavior for Custom User role for getting signature?

**Comment by fkuo-stripe** [comment]
Hi Eric, thanks for the report. We're looking into how best to resolve this.

**Comment by ericlackey** [comment]
@fkuo-stripe Any update on this? Unfortunately, my app isn't available for many users at my company because of this.

**Comment by ericlackey** [comment]
@fkuo-stripe Actually, I just had one of these users try it again and it appears to be working for them now. So, this might be fixed already.

**Comment by fkuo** [comment]
Hi @ericlackey, yes, sorry about the lack of update here. We've put in a fix that resolves the issue with calling fetchStripeSignature when using custom roles. We're still working on the full story of how custom roles work with Stripe Apps in general, but I'll close this issue as it has been resolved!

**Comment by fkuo-stripe** [comment]
Hi [@ericlackey](https://github.com/ericlackey), yes, sorry about the lack of update here. We've put in a fix that resolves the issue with calling fetchStripeSignature when using custom roles. We're still working on the full story of how custom roles work with Stripe Apps in general, but I'll close this issue as it has been resolved!
