### ISSUE TITLE
Calling fetchStripeSignature throws an error "App must be uploaded before calling fetchStripeSignature"

### ISSUE THREAD

**Issue by cching-stripe** [stripe/stripe-apps#717]
A partner has uploaded a new version to their Stripe App and is receiving the following error on app load since they are calling fetchStripeSignature to authenticate requests to their backend. 

This seems to only happen in live mode where as when they run the app in test mode, that error is not thrown.

Prior to the most recent app upload on 8/17, they had no issue with calling the stripe signature and running their app. The only change in their most recent app upload was an API endpoint change which does not affect the signature.

**Comment by Shedav** [comment]
the same issue

**Comment by cchalstrom-stripe** [comment]
A fix has been deployed.  Apologies for the inconvenience!
