### ISSUE TITLE
Allow layouts other than fit content in FlexView components

### ISSUE THREAD

**Issue by charlesw-stripe** [stripe/stripe-apps#722]
**Is your feature request related to a problem? Please describe.**
I’m trying to build another example Stripe app for stripe-apps/examples. It’ll include with a FocusView . I want the children to take up the entire FocusView container with two Boxes that are distributed vertically using space-between.  So far I’ve tried `alignY: stretch`, and `height: "fill"`  as `css` properties on a top level Box with no luck.

**Describe the solution you'd like**
A css property that allows me to build flexible layouts along the vertical axis like the `ContextView` or a change to the default behavior so that it aligns with the `ContextView`

**Describe alternatives you've considered**
I tried using the footerContent but it's not a good solution to my use case (a Table).

**Comment by dannygarcia-stripe** [comment]
@charlesw-stripe this should now be possible. The immediate content container for FocusView matches the flexbox styles of ContextView. Feel free to reopen if you are still having issues!
