### ISSUE TITLE
App ID doesn't match public app ID

### ISSUE THREAD

**Issue by dariodjuric** [stripe/stripe-apps#723]
**Describe the bug**

Yesterday, we requested a live install of two apps to our merchant account. The live install was done and the apps were working properly.

However, today both apps get the error "App ID doesn't match public app ID" when trying to obtain Stripe signature.

**To Reproduce**

1. Live install an app to a merchant that fetches signature using the Stripe API
2. Open the app
3. See error in the console

**Expected behavior**

Signature fetch should work as before.

**Screenshots**

This looks suspicious, but I can't tell for certain if that's a valid ID.

![image](https://user-images.githubusercontent.com/5459296/187925130-d9384762-8b56-45ff-ab80-e759458b9361.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 105.0.5195.52 

**Additional context**

The merchant account is acct_1KHHCIGGq1MJhrgL. All apps are currently failing there due to this error.

**Comment by tjfontaine-stripe** [comment]
Sorry for the disruption, this was an error on the Stripe side, and has subsequently been resolved. Please let us know if this reoccurs.
