### ISSUE TITLE
Responsive ButtonGroup is displayed out of order

### ISSUE THREAD

**Issue by jwright** [stripe/stripe-apps#732]
**Describe the bug**
We have a context menu that has 3 action button items in it (Complete, Edit, and Delete). That order is important to us because we want "Complete" to be the first available action as that is the most likely one users will want.

Here is the control code:

<img width="542" alt="CleanShot 2022-09-09 at 12 11 58@2x" src="https://user-images.githubusercontent.com/35017/189395156-6ef78def-e4b6-477a-a257-4bf50800495f.png">

However, the ButtonGroup control places the "Edit" button as the first button as seen here:

<img width="315" alt="CleanShot 2022-09-09 at 12 09 21@2x" src="https://user-images.githubusercontent.com/35017/189395298-8292df44-7a95-4056-8fd2-586beb310ea0.png">

This is the HTML that was rendered. The order is preserved here:

<img width="482" alt="CleanShot 2022-09-09 at 12 09 53@2x" src="https://user-images.githubusercontent.com/35017/189395380-aedb4c53-9d2b-49a9-ba4a-1b7e82874f91.png">

This may be by design since edit is the shortest text but I don't think the framework should choose the order for you.

Making this change to the control code produces the result we want but it is a hack.

![CleanShot 2022-09-09 at 12 10 31@2x](https://user-images.githubusercontent.com/35017/189395597-28e0e85a-f942-4e1a-b914-2190b2459508.png)

Produces the "correct result":

<img width="332" alt="CleanShot 2022-09-09 at 12 10 24@2x" src="https://user-images.githubusercontent.com/35017/189395659-e3ce052a-8452-4c41-af74-436ce8568146.png">

**To Reproduce**
1. Create a button group control with 3 items with the top item being longer than the next two items
2. Place button group inside a context view
3. Notice that the buttons are out of order

**Expected behavior**
The control should render in order of the button items.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser all

**Additional context**

**Comment by hoffman-stripe** [comment]
Hey there, @jwright. If you mark the "Complete" button as primary, it'll be collapsed into the overflow menu after the secondary buttons.

You're correct that which buttons are shown depends on how much space is available. This is by design. See the "Overflow collapsing" section of the `ButtonGroup` docs [here](https://stripe.com/docs/stripe-apps/components/buttongroup#collapse-button-groups). Specifically:

> Button groups responsively adapt to the space available in their container by collapsing buttons into an overflow menu. Primary buttons collapse after any other buttons, and larger buttons collapse first.

**Comment by jwright** [comment]
@hoffman-stripe Ok. I forgot about the `primary`value because I was under the impression that would change the UI to be a "primary" button but it does not seem to do that. 

I think this is fine but I would never expect the framework to change the ordering. Just my feedback but I will close this out. Thank you for the quick response.
