### ISSUE TITLE
Live reload not working as expected

### ISSUE THREAD

**Issue by dariodjuric** [stripe/stripe-apps#733]
**Describe the bug**

It seems that for me and for my teammates, the live reload has stopped working reliably in the last couple of weeks or so. We need to close and open the drawer to see changes in the UI code, while before it wasn't needed - the live reload just refreshed the app. We're seeing this issue on multiple apps.

**To Reproduce**

Create a simple component such as:

```
import { Box, ContextView } from '@stripe/ui-extension-sdk/ui';
import React from 'react';

export const MyTestComponent: React.FC = () => {
  return (
    <ContextView title="Test">
      <Box>test</Box>
    </ContextView>
  );
};
```
Follow the steps as shown in the video: https://share.cleanshot.com/SW5fSg

**Expected behavior**

Changes should be reflected immediately, and not be delayed by another refresh.

**Screenshots**

See video: https://share.cleanshot.com/SW5fSg

**Desktop (please complete the following information):**
 - OS: MacOS 12.5.1
 - Browser: Chrome
 - Version: 105.0.5195.102

**Additional context**

We're also using the latest Stripe CLI (1.12.0), apps plugin (1.4.0), and UI Extension SDK (8.3.0).

**Comment by dariodjuric** [comment]
Here is one additional video if it helps: https://share.cleanshot.com/KCv033

The app is started using the `--log-level trace` flag, but this only outputs some extra information after the start. The reload notification is the same. As can be seen in the video, the changes are always "late" by one reload cycle.

It's strange that this happens in all of our apps, and it did not happen until a couple of weeks ago. Something in our apps or in our setup must be triggering this, but we are not sure where to look. If we create a new app from scratch, the live reload works fine there.

Also, we see that the updated code is properly returned in http://localhost:4242/.build/ext.js right after modification. The updated code is also visible in Developer Tools / Sources / sandbox.html / localhost:4242, but the most recent change is not reflected in the UI:

![CleanShot 2022-09-15 at 12 21 29@2x](https://user-images.githubusercontent.com/5459296/190380622-d8a3c030-7cad-43f1-a12a-667ded234d0e.png)

**Comment by tennhard-stripe** [comment]
Thanks for bringing this to our attention. We were able to replicate the issue and are investigating further.

**Comment by tennhard-stripe** [comment]
Thanks again, @dariodjuric, for bringing this to our attention. Live Reloading should now function again as expected.
