### ISSUE TITLE
payment_intent_write permission does not allow payment intents to be confirmed

### ISSUE THREAD

**Issue by zemaj** [stripe/stripe-apps#735]
**Describe the bug**
Apps with `payment_intent_write` set can not confirm payment intents they create

**To Reproduce**
1. Create a new app
2. Give it the `payment_intent_write` permission
3. Add it to an account
4. Create a payment intent with that account using the app authentication
5. Attempt to confirm payment intent e.g. run `POST /v1/payment_intents/pi_xxxxx/confirm`
6. A 403 error will be thrown (see screenshot below)

**Expected behavior**
Payment intent should be confirmed

**Screenshots**
<img width="823" alt="Screen Shot 2022-09-15 at 7 59 40 pm" src="https://user-images.githubusercontent.com/28863/190536462-8fe8693a-ee4e-4eab-8a50-4279fba4111c.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 105

**Additional context**
Switching account back to OAuth connection with `read_write` scope resolves the problem. However it means that we're not able to migrate accounts using payment intent confirmation from OAuth to app authentication. Any accounts which install our Stripe app will see this functionality break.

**Comment by fkuo-stripe** [comment]
Hi, it looks like you're using payment intents through [Stripe Elements in stripejs](https://stripe.com/docs/payments/elements). If this is the case, you'll need to give your app the `elements_write` permission.

**Comment by svenugopal-stripe** [comment]
@zemaj ..following upon this. . is this still a blocker / issue ?

**Comment by zemaj** [comment]
Nope, all sorted by adding in the `elements_write` permission as well. Thanks!
