### ISSUE TITLE
Apps in production getting "App ID doesn't match public app ID"

### ISSUE THREAD

**Issue by dariodjuric** [stripe/stripe-apps#748]
**Describe the bug**

As of today, we are seeing our production apps getting "App ID doesn't match public app ID" error when invoking https://dashboard.stripe.com/v1/tailor/backend_signature.

The response is:

```
{"error":{"message":"3:App ID doesn't match public app ID","message_code":"account_error_invalid_format_extra","type":"invalid_request_error"}}
```

We've seen this error once before, on September 1st. The issue for that is #723.

**To Reproduce**

1. Open any production app.
2. See the error in the console

**Expected behavior**

Signature fetch should work as before.

**Screenshots**

<img width="1546" alt="CleanShot 2022-10-11 at 10 13 05@2x" src="https://user-images.githubusercontent.com/5459296/195035598-c17f952e-95a6-47a0-98cf-94d73c20354b.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 105.0.5195.52

**Additional context**

One of the merchants having this problem is acct_1KsRsgBy6bk0VByy.

**Comment by msindwan-stripe** [comment]
Hi @dariodjuric thanks for reporting! We're aware of the issue and are actively working to resolve it at the moment. We will provide updates as soon as possible

**Comment by msindwan-stripe** [comment]
The issue has been resolved! Merchants may need to reload their apps by refreshing the page
