### ISSUE TITLE
Support for MacOS 13 (Ventura)

### ISSUE THREAD

**Issue by PhilipAnd** [stripe/stripe-apps#757]
**Describe the bug**
I have installed the new Mac OS 13 (Ventura) and are trying to reinstall the CLI with:
`brew install stripe/stripe-cli/stripe `

I am receiving the error: 
`Your Command Line Tools (CLT) does not support macOS 13.`

I have ensured that the Xcode developer tools are up to date. Is the CLI not supported in the last macOS version, or do I need to downgrade?

**Comment by paulasjes-stripe** [comment]
This isn't an issue with Stripe Apps, but rather that Ventura doesn't ship with stable Command Line Tools yet. You can install the release candidate yourself here: https://developer.apple.com/download/all/?q=xcode (Command Line Tools for Xcode 14.1 Release Candidate 2 at time of writing).

**Comment by PhilipAnd** [comment]
Thanks @paulasjes-stripe

**Comment by SpecialKREDhat** [comment]
hello, and sorry about the late response. Yes I have not yet had a chance to configure more options into the stripe app. It is still in production. I am in search for a more secure app because from the looks of it, stripe does not configure well. Any suggestions?
