### ISSUE TITLE
Multiple user access before production.

### ISSUE THREAD

**Issue by SpecialKREDhat** [stripe/stripe-apps#767]
## Authentication
I need to properly asscess the stripe app withoutbexcess user flow potentialy alternering not yet official code lines 
- Data, Storage
- Asana, docker images. also not approved of

**Comment by auchenberg-stripe** [comment]
We have released External Testing for Apps to make this simpler. Checkout our docs at https://stripe.com/docs/stripe-apps/test-app

Does this solve your problem, @SpecialKREDhat ?

**Comment by SpecialKREDhat** [comment]
need Help
