### ISSUE TITLE
"Modal" dropdowns behind tabs

### ISSUE THREAD

**Issue by jwright** [stripe/stripe-apps#768]
**Describe the bug**
We have a bug that is happening on our production and development apps. I attached a gif of the issue below. The menus from the actions prop on the `AccordianItem` as well as from buttons are displaying *behind* the context view/tabs.

Have you seen this reported in other apps? Is this something that we need to change on our side? I just saw this happen in our development side last week.

**To Reproduce**
1. Create an accordion with a few buttons inside a button group as the action menu so it creates a context menu button
2. Place accordion control over a tabbed interface
3. Click on context menu

**Expected behavior**
The menu items rendered in front of the application.

**Screenshots**
![stripe-apps-context-menu-bug](https://user-images.githubusercontent.com/35017/203422238-70a91abc-e81a-438a-aa4f-20fb3a2018cd.gif)

**Desktop (please complete the following information):**
 - OS: [MacOS Monterey]
 - Browser [chrome AND safari]

**Comment by dariodjuric** [comment]
We've also noticed this - it happens on all apps that use a `Menu` popup.

**Comment by cchalstrom-stripe** [comment]
Thank you for reporting this, it looks like an issue that we need to fix on our end.

**Comment by jwright** [comment]
@cchalstrom-stripe Is there a plan for this? This bug makes our app and a lot of other totally useless and it has been a week.

**Comment by cchalstrom-stripe** [comment]
@jwright We are actively working on this and hope to have something out in the next day or two.

**Comment by cchalstrom-stripe** [comment]
I'm closing this out as the z-index issue should be fixed now.  There remains an issue where if the page is scrolled, the menu does not remain fixed to the button group, but that issue is lower priority to fix.  Thanks for reporting!
