### ISSUE TITLE
Cannot upload App

### ISSUE THREAD

**Issue by bdcorps** [stripe/stripe-apps#770]
**Describe the bug**
I updated my Stripe CLI and now I can't upload apps for publishing.

**To Reproduce**
1. Run "stripe apps upload"
2. See an error: `[ERROR] plugin.child.apps: plugin process exited: path=/Users/sukh/.config/stripe/plugins/apps/1.5.1/stripe-cli-apps pid=27008 error="exit status 2"`

**Expected behavior**

**Screenshots**
<img width="1087" alt="CleanShot 2022-12-05 at 11 35 13@2x" src="https://user-images.githubusercontent.com/6132555/205691797-109e618c-cce5-4833-8dcb-b9a248a3babd.png">

**Desktop (please complete the following information):**
- Stripe CLI: 1.13.6
- Node: 18.12.1
- OS: Macbook M2

**Comment by chaves-stripe** [comment]
Hi there! The team is looking into this. To help us with our debugging, do you mind sharing the output from the command `stripe apps upload --log-level debug`? Thanks so much!

**Comment by bdcorps** [comment]
I tried this again without changing the Stripe CLI version and today it's working. Can be safely closed.

**Comment by SJ057** [comment]
I am getting same issue while trying to start app on local.

[Mon, 12 Dec 2022 18:31:32 IST] DEBUG config.Config.InitConfig: Using profiles file path=C:\Users\shyam.jadhav\.config\stripe\config.toml
[Mon, 12 Dec 2022 18:31:32 IST] DEBUG config.Config.GetProfilesFolder: Using profiles file path=C:\Users\shyam.jadhav\.config\stripe
[Mon, 12 Dec 2022 18:31:32 IST] DEBUG cmd.pluginCmd.runPluginCmd: Running plugin...
[Mon, 12 Dec 2022 18:31:32 IST] DEBUG config.Config.GetProfilesFolder: Using profiles file path=C:\Users\shyam.jadhav\.config\stripe
[Mon, 12 Dec 2022 18:31:32 IST] DEBUG config.Config.GetProfilesFolder: Using profiles file path=C:\Users\shyam.jadhav\.config\stripe
[Mon, 12 Dec 2022 18:31:33 IST] DEBUG Tearing down plugin before exit
2022-12-12T18:31:33.479+0530 [ERROR] plugin.child.apps: plugin process exited: path=C:\Users\shyam.jadhav\.config\stripe\plugins\apps\1.5.1\stripe-cli-apps.exe pid=25212 error="exit status 2"
[Mon, 12 Dec 2022 18:31:33 IST] DEBUG pluginTemplateCmd.runPluginCmd: Plugin command 'apps' exited with error: unexpected EOF

**Comment by R-Inbarasu** [comment]
I'm also facing same issue while trying to upload the app.

MT202102-0153:backend inbarasu$ stripe apps upload --log-level debug
[Tue, 20 Dec 2022 11:30:28 IST] DEBUG config.Config.InitConfig: Using profiles file path=/Users/inbarasu/.config/stripe/config.toml
[Tue, 20 Dec 2022 11:30:28 IST] DEBUG config.Config.GetProfilesFolder: Using profiles file path=/Users/inbarasu/.config/stripe
[Tue, 20 Dec 2022 11:30:28 IST] DEBUG cmd.pluginCmd.runPluginCmd: Running plugin...
[Tue, 20 Dec 2022 11:30:28 IST] DEBUG config.Config.GetProfilesFolder: Using profiles file path=/Users/inbarasu/.config/stripe
[Tue, 20 Dec 2022 11:30:28 IST] DEBUG config.Config.GetProfilesFolder: Using profiles file path=/Users/inbarasu/.config/stripe
⬆ You are about to upload your Stripe App Gist for Stripe version "1.0.0" to Mallow-tech.
Would you like to proceed: Y
2022-12-20T11:30:38.756+0530 [ERROR] plugin.child.apps: plugin process exited: path=/Users/inbarasu/.config/stripe/plugins/apps/1.5.1/stripe-cli-apps pid=27305 error="exit status 2"
[Tue, 20 Dec 2022 11:30:38 IST] DEBUG Tearing down plugin before exit
[Tue, 20 Dec 2022 11:30:38 IST] DEBUG pluginTemplateCmd.runPluginCmd: Plugin command 'apps' exited with error: unexpected EOF

stripe version 1.13.6
