### ISSUE TITLE
External Test switching version stuck at saving

### ISSUE THREAD

**Issue by madeincosmos** [stripe/stripe-apps#776]
**Describe the bug**
External test stuck while switching a version

**To Reproduce**
1. Upload new version of a Stripe App
2. Go to developers -> Stripe App -> External test
3. Switch current app version
4. See "Saving" being stuck (more than a week now)

**Expected behavior**

A version distributed in External test switched to a new one

**Screenshots**

![Zrzut ekranu 2022-12-17 o 18 14 13](https://user-images.githubusercontent.com/17686109/208253486-cc0aeaa3-6786-4abd-8c3e-e6c4f2baf4c9.png)

**Additional context**
The app is `com.sellfilesonline.app`

This is stuck for almost a week. I think the request that broke it was `req_4g4euQ4B7Y63NJ `

**Comment by tjfontaine-stripe** [comment]
@madeincosmos thanks for the report, and sorry for the delay -- we're taking a look into this right now.

**Comment by tjfontaine-stripe** [comment]
@madeincosmos unfortunately the fix is a little more involved than I hoped, we'll be fixing this issue on our side and will ping on this issue when it's resolved.

**Comment by madeincosmos** [comment]
Thank you! We can wait a bit :)

**Comment by svenugopal-stripe** [comment]
@madeincosmos We made a fix on our end. Could you please confirm if the issue is resolved ?

**Comment by madeincosmos** [comment]
Thank you so much, yes - I can confirm it works now. I can get back to work :)
