### ISSUE TITLE
Accounts with app installed not visible in Connect

### ISSUE THREAD

**Issue by madeincosmos** [stripe/stripe-apps#777]
**Is your feature request related to a problem? Please describe.**

I have 2 use cases:

1. I want to access all the accounts in which my app is installed, so I can monitor if everything is ok, read metrics, etc.
2. I want to read Account Name and Account Support Email for a specific account. My app will send emails for merchants behalf and I want to use these fields for the From field in the emails my app sends.

**Describe the solution you'd like**

- See all the accounts that have installed my app in the https://dashboard.stripe.com/connect/accounts/overview tab
- Have all this data in `/v1/accounts` endpoint
- Have all this data in the `/v1/account` endpoint

Now, when I try to read from /v1/account, I get an error message explaining that `account_read` permission is needed. But there is no way for me to add that permission in the App Manifest. 

I think `/v1/accounts` has this data and is accessible and exposed, despite `/v1/account` NOT having it, which feels like a bug one way or the other.

Mainly I want to know what behaviour is expected in the production app, since the above is very inconsistent:

- Dashboard list DOES NOT work
- /v1/account DOES NOT work
- `/v1/accounts` seems to work.

**Describe alternatives you've considered**

I will use `userContext.account.name` and `getDashboardUserEmail` in JS to save this data, but this is not ideal.
I also need to save the webhook data from when app is installed to be able to get a list of accounts that have installed the app.

**Comment by chaves-stripe** [comment]
Hi there! the `connected_account_read` permissions listed [here](https://stripe.com/docs/stripe-apps/reference/permissions) should give you this access.  Note you will only get access for accounts that install the any forward versions that have that permission requested in the manifest!

 I can see how the error message is misleading so we can take a look at that. 

Let me know if this helps unblock you

**Comment by madeincosmos** [comment]
Thank you - yes, I think I can work with that!
