### ISSUE TITLE
Re-installing an app with a wider permission scope triggers a 500 error

### ISSUE THREAD

**Issue by madeincosmos** [stripe/stripe-apps#778]
**Describe the bug**
Re-installing an app with a wider permission scope triggers a 500 error

**To Reproduce**
1. Install a version of the app on a merchant account
2. Add new permissions in using `stripe apps grant`
3. Upload a new version of the app
4. Pin it for external testers
5. Open the link to install on the account it was previously installed on (step 1)
6. Agree to wider scope of permissions
7. See 500 error

**Expected behavior**
Not having a 500 error

**Additional context**
Requests:

https://dashboard.stripe.com/logs/req_J4N88W9K4TBRtb
https://dashboard.stripe.com/logs/req_iPuEPHNaku7UZv

**Workaround**

Now I make a habit of:

1. Removing the app
2. Installing it again with a link.

**Comment by fkuo-stripe** [comment]
Hi @madeincosmos we made a fix a couple weeks ago to address this issue and reinstalling in this way should work correctly now. Please feel free to re-open the issue or file a new one if you encounter it again, thanks!

**Comment by madeincosmos** [comment]
Thank you!
