### ISSUE TITLE
How to simulate app install on connected account?

### ISSUE THREAD

**Issue by benfoster** [stripe/stripe-apps#781]
## Your Problem

When I run an application locally with `stripe apps start` I am prompted to choose the account to which the app should be installed.

It is (now) my understanding that installing an app enables the target account as a connected account (this needs to be much clearer in the docs btw) giving the app "owner" the ability to make requests to the Stripe API based on the permissions that are configured in the app manifest.

How should I best test the following scenario:

- I have created one test account 1 to represent my app owner
- I have created another test account 2 to represent my app user
- When the app is installed I want to receive charge events to a backend app
- Goal: After I install the app, I make a test payment under the Account 2, and receive webhooks to the backend-app.

As I mentioned, I've been going around in circles regarding the authentication flow and thought that after the user installs the app I would still need to set them up via connect using https://stripe.com/docs/connect/oauth-reference.

**Comment by jdilla-stripe** [comment]
Hi Ben:

We are right about to launch an external testing feature that makes this a lot easier.

If you want, I can add you to our private beta for this feature. I'll need the account id for the developer account and the merchant account you want to do testing on. Send me an email to jdilla at stripe.com

**Comment by Matthieu-OD** [comment]
A stripe member from the discord redirected me here.

My goal is to give Stripe a test stripe account with my stripe marketplace app installed on it so they can review my app.
I can't find any way to do this.

@jdilla-stripe, could your solution fix my issue?

**Comment by Matthieu-OD** [comment]
I had a confirmation from the support that it would solve my issue. I'm sending you an email to integrate this private beta.
I hope you'll be able to add me to it.
