### ISSUE TITLE
Calling Stripe's API from within a UI extension

### ISSUE THREAD

**Issue by benfoster** [stripe/stripe-apps#782]
## Your Problem

Is it possible to call Stripe APIs from within a UI extension, on behalf of the user, without needing to specify my secret key (e.g. publishable key) or do I always need to have a backend API if I want to make requests to Stripe.

There are examples in [the docs](https://stripe.com/docs/stripe-apps/build-ui#code-sample-update-customer-name) of doing this but it's not clear whether the `STRIPE_API_KEY` value is injected automatically?

## Existing Documentation URLs (If applicable)

https://stripe.com/docs/stripe-apps/build-ui#code-sample-update-customer-name

**Comment by ericfrank-stripe** [comment]
Hey @benfoster, yes, what you're describing is possible. The `STRIPE_API_KEY` value is injected automatically when you import it from the UI Extension SDK:

```
import {STRIPE_API_KEY} from '@stripe/ui-extension-sdk/http_client';
```

I'll close this issue for now, but if your problem isn't solved feel free to comment here and we can reopen it.
