### ISSUE TITLE
Question about the intended usage of SignInView

### ISSUE THREAD

**Issue by dariodjuric** [stripe/stripe-apps#804]
Hello Stripe team, I have a question about the intended usage of the [SignInView component](https://stripe.com/docs/stripe-apps/components/signinview) in the context of an OAuth flow.

If the primary action is a sign-in button, and we use a `href` in the `primaryAction` field, this will open the external auth page in a new tab. The user can complete the OAuth flow in the new tab and get redirected to the Stripe dashboard, but the original tab will keep showing the sign-in component. The user will have two tabs open at that point. How can the dashboard detect that the user has successfully authenticated in the external site? We have no way of knowing that the user has clicked the sign-in button. There's an `onPress` property, but it appears it cannot work together with a `href` - only one of them can be used.

Or, is the intended usage to have a signup button in the _primary action_, and have the sign-in in the _footer_? If the sign-in button is in the footer, then we can use a custom button there and we can have more control.

**Comment by ericfrank-stripe** [comment]
Hi Dario, it sounds like the easiest solution is for us to allow both `href` and `onPress` on the action as you've suggested. I've added this to our backlog and we'll post here when it's complete. Thanks!

**Comment by dariodjuric** [comment]
@ericfrank-stripe would it also be possible to have the href target configurable as well? (New tab or current tab.)

**Comment by ericfrank-stripe** [comment]
@dariodjuric Yes, we're working on making that property configurable as well.

**Comment by ericfrank-stripe** [comment]
We've just released SDK version `8.6.0`, which allows `onPress` and `href` to be used at the same time and also allows a configurable `target` property. See: https://www.npmjs.com/package/@stripe/ui-extension-sdk/v/8.6.0
