### ISSUE TITLE
Clear an uncontrolled Textfield

### ISSUE THREAD

**Issue by bdcorps** [stripe/stripe-apps#828]
**Is your feature request related to a problem? Please describe.**
When the user enters text in a TextField, the app should be able to clear input when the action is completed. Currently, it is not possible to do this with an uncontrolled Textfield as is recommended in [the docs](https://stripe.com/docs/stripe-apps/how-ui-extensions-work#use-uncontrolled-components-for-interactions).

Scenario:
The user adds a URL for an image to be uploaded and presses the submit button. Once the image is finished uploading, the image URL input should be empty.

**Describe the solution you'd like**
There should be a way to clear an uncontrolled Textfield. 

**Describe alternatives you've considered**

1. I've tried using `defaultValue`:

```
<TextField
name="image"
defaultValue={currentImageUrl}
onChange={(e) => {
    setCurrentImageUrl(e.target.value)
}}
label="Image URL"
/>
```
Of course updating the `currentImageUrl` state variable does not update the Textfield value. 

2. I've tried:

```
<TextField
name="image"
defaultValue={currentImageUrl}
onChange={(e) => {
    setCurrentImageUrl(e.target.value)
}}
value={!currentImageUrl ? '' : undefined}
label="Image URL"
/>
```

This one works when the user tries to enter text by keyboard. The input does not work if they copy/paste text in.

**Additional context**
There's also no `ref` available to achieve this that way.

**Comment by ericfrank-stripe** [comment]
Hi @bdcorps, the recommended use of uncontrolled inputs is a limitation of the security mechanism we use to run 3rd party code safely within the Stripe Dashboard. To solve this kind of issue, I recommend you try using a `key` on the field, which remounts it and reverts the field to the `defaultValue` or a blank value if no `defaultValue` exists. Here's some pseudocode.
```
const MyComponent = () => {
  const [key, setKey] = React.useState(0);
  return (
    <>
      <Button onPress={() => setKey(key + 1)}>Clear</Button>
      <TextField
        key={key}
        (your other props)
      />
    </>
  );
};
```

We have no plans to change our security mechanism at the moment, so I'll close out this issue, but feel free to respond if you have any other questions.
