### ISSUE TITLE
Integrating Vercel with Stripe Apps

### ISSUE THREAD

**Issue by JayateerthDambal** [stripe/stripe-apps#830]
I am trying to integrate my vercel backend with stripe apps.
I am getting an error like

**_[12:01:10] ERROR stripe-app.json
found violation for connect-src "https://stripe-backend-k7b4-jayateerthdambal.vercel.app/": path cannot be empty_**

How to resolve this issue?

**Comment by auchenberg-stripe** [comment]
Hi @JayateerthDambal 

It looks like you need to add the URL for your Backend hosted on Vercel to your app's CSP. See https://stripe.com/docs/stripe-apps/build-ui#use-third-party-apis for more details
