### ISSUE TITLE
Promo Codes permission not available

### ISSUE THREAD

**Issue by bdcorps** [stripe/stripe-apps#835]
**Describe the bug**
I am looking to create a Promotion Code for my connected user but I am not able to do so because of `No permissions` error.

![image](https://user-images.githubusercontent.com/6132555/232547144-f4a5cb67-f18e-4b6c-aeda-1a47f4f1378f.png)

These are permissions the user already have:
```
subscription_read,customer_read,connected_account_read,user_email_read,coupon_read,coupon_write,product_read,invoice_read,invoice_write,quote_read,credit_note_read,credit_note_write
```

**To Reproduce**
1. Add these permissions to your Stripe app: `subscription_read,customer_read,connected_account_read,user_email_read,coupon_read,coupon_write,product_read,invoice_read,invoice_write,quote_read,credit_note_read,credit_note_write`
2. Try to run: 
```
 const promotionCode = await stripe.promotionCodes.create({
    coupon: couponId,
}, { stripeAccount: accountId });
```
3. See Error: No Permissions for this resource

**Expected behavior**
I should be able to create a promocode for my connected user.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] N/A
 - Browser [e.g. chrome, safari] N/A
 - Stripe CLI - N/A

**Additional context**
- Request ID: `req_HJFlZ7oKgT4A3q `
- I have already tried adding `promotion_code_write` and it doesn't recognize the permission when I try to upload the app

**Comment by chaves-stripe** [comment]
thanks for reporting @bdcorps ! We are working on adding a new permission to handle this case and will let you know when it is available

**Comment by chaves-stripe** [comment]
hi @bdcorps . promotion_code_read and promotion_code_write are now available to use
