### ISSUE TITLE
stripe apps upload with a different manifest

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-apps#841]
We can specific a specific manifest file with the command `stripe apps start --manifest stripe-app.dev.json`.

How do we specify a specific manifest file with the `stripe apps upload` command?

**Comment by auchenberg-stripe** [comment]
Hi @clement911 

We don't support this today, as our multiple manifest support works with the baseline config as the production one with a special one for `dev` as you have outlined. https://stripe.com/docs/stripe-apps/reference/app-manifest#extended-manifest

How do you ideally want this to work in your scenario/workflow?

**Comment by clement911** [comment]
Hi @auchenberg-stripe,

Thanks for your response.

Originally, we planned on creating 2 versions of our app. 1 for prod and 1 for testing.
For example,  com.example.app and com.example.testing-app
We wanted to be able to have 2 manifest files next to each other and be able to upload either the testing app or the prod app.

However, I don't think we really need this anymore.
You see, originally I thought that we could only use `stripe apps start` on the stripe account where the app is defined.
I've since realized that we can use it on any account.

I'll close this.
