### ISSUE TITLE
`ContextView` cannot fill app drawer's full height. Footers don't align to bottom.

### ISSUE THREAD

**Issue by tvanantwerp** [stripe/stripe-apps#845]
**Describe the bug**
Cannot fill the height of the app drawer. Items that ought to align to the bottom of the drawer are not aligned.

**To Reproduce**
1. Create a `ContextView` in a Stripe App.
2. Add some children and `footerContent` to the `ContextView`.
3. Observe that the footer is not aligned to the bottom of the drawer.

**Expected behavior**
The footer should be aligned to the bottom of the drawer.

**Screenshots**
<img width="268" alt="image" src="https://user-images.githubusercontent.com/2487968/235973061-5625b570-850c-4a30-8552-1a774b83aeac.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 112.0.2
 - Stripe SDK version: 8.6.0

**Additional context**

While developing, I observed that content previously aligned to the bottom of the app drawer no longer was at the bottom. Originally the content had been inside only a `Box` with height set to fill and stack set to y with space-between distribution. But we later put this inside a `ContextView`, which it should've been in. After that, the content no longer took up all height in the drawer.

I decided to try putting the content which should've been bottom-aligned into the `ContextView`'s `footerContent` to fix it, but it made no difference. So I created the simplest test possible: a single `ContextView` with one `Box` child and another `Box` for `footerContent`. The problem persisted: `footerContent` was not aligned to the bottom of the drawer.

Because the `ContextView` itself, when rendered to the DOM, has no height set, I cannot use `height: 'fill'` in any children to manually take up all drawer height. CSS's `height: 100%` only takes up 100% of the parent's height. And since the rendered `ContextView` has no set height, it's interpreted as the height necessary for the content and no more. The `ContextView` itself doesn't take CSS props, so I cannot force it to have a height.

**Comment by tvanantwerp** [comment]
This has also been observed in the `SignInView` component.

**Comment by ericfrank-stripe** [comment]
This issue has been resolved.
