### ISSUE TITLE
What is the permission to request access to reviews?

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-apps#847]
As a Stripe extension we could load radar reviews (https://stripe.com/docs/api/radar/reviews)

I see no permissions to access these reviews as a Stripe app.

**Comment by fkuo-stripe** [comment]
Hi @clement911, the `review_read` and `review_write` permissions are now available for Stripe Apps and can be added using `stripe apps grant` by upgrading your Stripe Apps CLI plugin to 1.5.9 or newer (`stripe plugin upgrade apps`).
