### ISSUE TITLE
Add feature to retrieve accepted permissions in the app

### ISSUE THREAD

**Issue by tvanantwerp** [stripe/stripe-apps#851]
**Is your feature request related to a problem? Please describe.**
Some new features in an updated app require the acceptance of new Stripe permissions. We are trying to keep these features gated for users who have not yet accepted the permissions. However, we are struggling to verify permissions.

Ideally the app would expose an API to check which permissions have been accepted on the account. But without this feature, we have to resort to making read calls to Stripe API endpoints via the Stripe SDK. Unfortunately, this is a brittle way to check for permissions. It also doesn't help us check if required write permissions were accepted, as we don't want to write dummy data to check a permission.

The documentation around error codes for Stripe Apps permissions is not very thorough. We've seen both `more_permissions_required_for_session` and `more_permissions_required_for_application` while trying to figure out what the error code should be. Also, the error type is `invalid_request_error`—but wouldn't it make more sense to use the `permission_error` type?

In some test cases, the 403 errors don't even return a response body, so we cannot determine what the error is. We don't know why this is happening and have struggled to reliably reproduce it.

**Describe the solution you'd like**
We would like an easy to implement permissions check as part of the Stripe Apps SDK.

**Describe alternatives you've considered**
As a second best solution, we'd accept better documentation and assurances around permissions errors that would currently be thrown. Though this doesn't help with determining write permissions and is overall still brittle.

**Additional context**
We have production users encountering permissions errors when trying to use features they cannot presently use. They are not prompted to go update permissions because our app has failed to detect that the permissions are missing. This problem makes it difficult to launch new app features reliably.

**Comment by kafrifa-stripe** [comment]
hey @tvanantwerp! The latest release of the [UI Extension SDK](https://stripe.com/docs/stripe-apps/reference/extensions-sdk-api) exposes the function `isPermissionAuthorized` to check which permissions have been authorized on an account. We also expose a new [context](https://stripe.com/docs/stripe-apps/reference/extensions-sdk-api#appContext) containing authorized app permissions and content security policy. This issue should now be resolved.
