### ISSUE TITLE
`onDismiss` in a `Banner` inside `SettingsView` will also trigger `onSave`

### ISSUE THREAD

**Issue by tvanantwerp** [stripe/stripe-apps#858]
**Describe the bug**
When a `Banner` is used inside a `SettingsView`, and the `onDismiss` function is triggered by the user when clicking the X in the `Banner`, it _also_ will trigger the `onSave` function given to the `SettingsView`.

**To Reproduce**
Create a `SettingsView` with a `Banner`. The `Banner` should have an `onDismiss` function, and the `SettingsView` should have an `onSave` function. Here is an example of the component used in our testing:

```ts
// src/views/Settings.tsx
import { useState } from 'react';

import { Banner, Box, Inline, SettingsView } from '@stripe/ui-extension-sdk/ui';

const Settings = () => {
  const [hasSaved, setHasSaved] = useState(false);
  const [showBanner, setShowBanner] = useState(true);

  const onSave = () => {
    setHasSaved(true);
  };
  const onDismiss = () => {
    setShowBanner(false);
  };

  return (
    <SettingsView onSave={onSave}>
      <Box css={{ stack: 'y', gap: 'medium' }}>
        {showBanner && (
          <Banner
            title="Test banner"
            onDismiss={onDismiss}
            description="This Banner should go away when the X is pressed"
          />
        )}
        <Box>
          The onSave function has been called:{' '}
          <Inline css={{ fontWeight: 'bold' }}>{String(hasSaved)}</Inline>
        </Box>
      </Box>
    </SettingsView>
  );
};

export default Settings;

```

**Expected behavior**
The `Banner`'s `onDismiss` function will be called. The `onSave` function for the `SettingsView` should _not_ be called.

**Screenshots**

https://github.com/stripe/stripe-apps/assets/2487968/ae37211d-4ff9-4d4b-847e-9dab9007bffe

**Desktop (please complete the following information):**
 - OS: macOS 13.3
 - Browser: Firefox
 - Version: 112.0.2

**Comment by ericfrank-stripe** [comment]
This issue should now be resolved.
