### ISSUE TITLE
Toast is never at the bottom of the view. (ShowToast)

### ISSUE THREAD

**Issue by erikahendsel** [stripe/stripe-apps#864]
**Describe the bug**
Toast will take the initial height of the screen and always show the toast at the bottom of the initial page load.  If the user scrolls down the page, the toast does not follow. It seems to be at a fixed position on the page. 
**To note:** The page loads all the contents dynamically. 

**To Reproduce**
1. Create a settings view. 
2. Make sure you have a lot of content, so the user can scroll down the page.
3. Have a on click action to trigger the Toast.
4. Refresh the page.
5. Scroll down the page.
6. On a click action, trigger a showToast('Toast triggered', { type: "success" });

**Expected behavior**
The toast should always be at the bottom of the view. 

**Screenshots** 
Video:
https://github.com/stripe/stripe-apps/assets/38254577/c542515b-e90f-4e9f-8774-b70f205f1035

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 
 - Version 114.0.5735.199

**Comment by ericfrank-stripe** [comment]
This issue should now be resolved.

**Comment by erikahendsel** [comment]
Thank you for the fix. It is working very well now!
