### ISSUE TITLE
Can't install app for external test when adding the review read and review write permission to the app

### ISSUE THREAD

**Issue by akhenia-palash** [stripe/stripe-apps#888]
**Describe the bug**
My app needs the review read and review write permission and when i add it and try to do external tests, i am unable to install the app for some reason

**To Reproduce**
stripe apps grant permission "review_read" "to capture the reviews generated"
stripe apps grant permission "review_write" "to edit the reviews generated"

**Expected behavior**

**Screenshots**

<img width="1408" alt="Screenshot 2023-06-22 at 2 41 34 AM" src="https://github.com/stripe/stripe-apps/assets/26880667/dc5c6c57-3280-473a-826b-e48882cf6e14">

**Desktop (please complete the following information):**

**Additional context**

**Comment by svenugopal-stripe** [comment]
@akhenia-palash could you please share your app's public id ?. Also is your app a public app ?

**Comment by sca1235** [comment]
> @akhenia-palash could you please share your app's public id ?. Also is your app a public app ?

It is not public yet. `com.trust-swiftly.stripe-app` is the app id.

Our `0.1.0` version has the review permissions and broken. The `0.0.9` we were trying with the external test.

**Comment by chaves-stripe** [comment]
@akhenia-palash @sca1235 This should be resolved. Can you please test this again? Thank you!
