### ISSUE TITLE
Request to add shipping_rate_read and shipping_rate_write to list of allowed permission options

### ISSUE THREAD

**Issue by bensontrent** [stripe/stripe-apps#904]
I'm developing app to allow users to create shipping labels for USPS, UPS, FEDEX, DHL and others.   I need a way to read shipping rates so I can offer users the ability to map a Shipping Rate to a default carrier and a service level.

The [list of allowed Object Permissions](https://stripe.com/docs/stripe-apps/reference/permissions) doesn't allow reading or writing to the Shipping Rates API.  

I can use these two commands in the CLI:

```
stripe apps grant permission "shipping_rate_read" "To map shipping rates to carriers and services"
stripe apps grant permission "shipping_rate_write" "To add metadata to shipping rates to set default carrier and shipping options"
```
But those permissions are not yet supported on the backend. 

//stripe-app.json
![image](https://github.com/stripe/stripe-apps/assets/5982592/8fe4d650-9f90-4951-89b8-b1ca9158394d)
![image](https://github.com/stripe/stripe-apps/assets/5982592/c782f80b-d898-4b2e-8b40-5ca84fa4ef47)

I suppose it might be possible to circumvent this by asking the User to create a restricted Stripe API key and save it to the Secret Store, but I'd like to avoid that extra step.

Is it possible to allow these permissions?

**Comment by chaves-stripe** [comment]
@bensontrent we can add a new permission! To get a bit more context, does your use case require the write permission, and if so how will you use that? Or is it just reading? Thanks!

**Comment by bensontrent** [comment]
That's great! Thank you for you quick response.  I need write permissions as well.  In my app settings, I'll have an interface to allow the user set defaults for each shipping rate, so they wouldn't need to manually select the carrier and service level each time an invoice is created. It would be nice to open up the dashboard view options to shipping rates as well, but I can handle this in my settings just fine.  Thanks again!

![image](https://github.com/stripe/stripe-apps/assets/5982592/4c6ca9e6-6d14-48ae-bf4f-7cfc1fc40f3f)

**Comment by chaves-stripe** [comment]
hi @bensontrent! These permissions should be available for you now!
