### ISSUE TITLE
Documentation for Data Store Write is missing

### ISSUE THREAD

**Issue by bensontrent** [stripe/stripe-apps#926]
In the docs, at https://stripe.com/docs/stripe-apps/reference/permissions

It shows permissions for data_store_read and data_store_write:

![image](https://github.com/stripe/stripe-apps/assets/5982592/d4042858-2608-4c40-a457-7dfe5cedc3ce)

But clicking on the link to https://stripe.com/docs/api/datastore gives a 404 

![image](https://github.com/stripe/stripe-apps/assets/5982592/352b581f-f347-4530-bd17-dfd6cf024873)

In the example apps, there is an example app for data-store. 

This app only shows how to read the data--it doesn't show how to modify, delete or write to the data store.

Is data store still an active feature?  If so, can we get more info on how to use it?

**Comment by fkuo-stripe** [comment]
Hi @bensontrent, the data store service is currently in private beta and we've removed that reference in the permissions documentation to avoid confusion. Stay tuned for more info - the example app can serve as a sneak peek!
