### ISSUE TITLE
Graduated pricing prices shows mismatched fees after creation.

### ISSUE THREAD

**Issue by leo-budgetsimple** [stripe/stripe-apps#932]
**Describe the bug**

**To Reproduce**
Go to any product
Create a graduated pricing Price
Click on '...' of the newly created pricing
See the mismatched prices

**Expected behavior**
Shoud show correct pricing

**Screenshots**
[Video Example](https://www.loom.com/share/1a6818a889004205a5adcab390405668)

**Desktop (please complete the following information):**
Google Chrome Version 116.0.5845.110 (Official Build) (64-bit)

**Additional context**
I think this is not only a visual issue because when using the api we subscribe an user to this product with this graduated price  the amount_due of the latest_invoice in the Subscription object is 0 when it should be the one that we set.

Also prices are being shared between products

**Comment by gabrielhurley-stripe** [comment]
Hi! This github repository is specifically for issues with the Stripe Apps SDK or app developer tooling. This issue won't get the attention it needs here.

I would recommend reporting the issue through our [Contact Support](https://support.stripe.com/contact/) page so it can get routed to the correct team, and if it's a known issue you'll get an answer right away.
