### ISSUE TITLE
Feature or documentation request: Add "disabled" property to Tooltip component

### ISSUE THREAD

**Issue by bensontrent** [stripe/stripe-apps#938]
It would be nice to have a disabled property on Tooltip to conditionally show the Tooltip popup.

[The example docs for Tooltip](https://stripe.com/docs/stripe-apps/components/tooltip) show a disabled button that shows a Tooltip that I imagine we would only want to show if the child element itself was in some state.

![disabled-toolip](https://github.com/stripe/stripe-apps/assets/5982592/c8ca117b-e195-4459-819f-eaf3e9dba37f)

I have several places in my code I'd like to offer a similar explanation via Tooltip, but only if the child element is in some conditional state.

### Preferred behavior:

```jsx
<Tooltip disabled={isDisabled} trigger={<Button onPress={undefined} disabled={isDisabled}>Immediate</Button>}>
 An explanation why this button is disabled
</Tooltip>
```

An alternative is to duplicate the trigger node behind another conditional which can get messy:

```jsx
{isDisabled ? <Tooltip delay={isDisabled ? 60 : 1 } trigger={<Button onPress={undefined} disabled={true}>Immediate</Button>}>
 An explanation why this button is disabled
</Tooltip> : <Button onPress={undefined} >Immediate</Button>}
```

I JUST realized as I was writing this: this could be accomplished by adding an extremely long delay time, but it wasn't immediately apparent in the docs.  Perhaps as an alternative to adding a new feature, this could be added to the docs:

## Disabling a tooltip

```jsx
<Tooltip delay={isDisabled ? 60000 : 1 } trigger={<Button onPress={undefined} disabled={isDisabled}>Conditionally disabled ToolTip</Button>}>
 An explanation why this button is disabled
</Tooltip>
```

**Comment by gabrielhurley-stripe** [comment]
Apologies for the slow response. What you want is possible with code like this:

```
<Tooltip
    type="description"
    trigger={
        <Button type="primary" disabled>
        Primary
        </Button>
    }
    >
    This is an explanation for the button being disabled
</Tooltip>
```

You're right that that isn't immediately obvious from the docs. I'll flag that we should update the docs with this pattern to the team. Thanks!
