### ISSUE TITLE
Cannot upgrade apps plugin

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-apps#939]
I am trying to run `stripe plugin upgrade apps` but get the following error.

```
Unable to refresh plugin manifest, continuing with cached manifest...
> could not install plugin 'apps'
you don't seem to have access to this plugin
```

I tried running the terminal as an admin, but that didn't help

**Comment by clement911** [comment]
It did fix it thank you @ngrubb-stripe 
It would be great if this was automatically handled by the command, or at least show a help message.

**Comment by ngrubb-stripe** [comment]
Glad to hear it! Totally agree - we will work toward improving the error message and providing a better experience when this occurs.

**Comment by gabrielhurley-stripe** [comment]
The error message issue is tracked internally. Closing this specific issue as resolved.
