### ISSUE TITLE
stripe apps start stuck on accepting T&Cs

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-apps#940]
I'm trying to run `stripe apps start --manifest stripe-app.dev.json`

It's opening a tab to accept T&Cs.
The tab says I can close and return to the command line, but the command line doesn't seem to detect anything and is stuck..

![image](https://github.com/stripe/stripe-apps/assets/3426504/f6d3a8a6-d0eb-4173-a196-c1c5f7c8bbbf)

![image](https://github.com/stripe/stripe-apps/assets/3426504/8ea09465-e2f4-4c40-9ed4-a6b6b62cb8f0)

**Comment by gabrielhurley-stripe** [comment]
Can you confirm you're using that latest version of the CLI and apps plugin? We had a similar report recently where that was the issue.

**Comment by gabrielhurley-stripe** [comment]
And yes, we have an internal ticket to improve the UX when that _is_ the problem :-)

**Comment by gabrielhurley-stripe** [comment]
Nevermind, I just saw your other issue about being unable to upgrade the plugin. That'd be the problem here. Let us investigate that issue instead.

**Comment by clement911** [comment]
This worked again once I applied the work around suggested on https://github.com/stripe/stripe-apps/issues/939

**Comment by gabrielhurley-stripe** [comment]
Great. Glad it's sorted. Have a great day!
