### ISSUE TITLE
`stripe apps secrets` is a documented CLI command, but not available

### ISSUE THREAD

**Issue by tvanantwerp** [stripe/stripe-apps#952]
**Describe the bug**

The API docs have examples for how to interact with the Secret Store from the Stripe CLI. But these examples do not work.

```
stripe apps secrets find  \
  --name="example" \
  -d "scope[type]"=account
Unknown command "secrets" for "stripe apps".
See "stripe apps --help" for a list of available commands.
```

**To Reproduce**
1. [Install the Stripe CLI](https://docs.stripe.com/stripe-cli#install) and the [Stripe Apps plugin](https://docs.stripe.com/stripe-apps/reference/cli#install-cli-plugin) for the CLI
2. Go to the [API documentation for the Secret Store](https://docs.stripe.com/api/apps/secret_store/find) and change the example code to use the Stripe CLI
3. Attempt to use one of the documented examples, e.g., `stripe apps secrets find ...`
4. Get the error `Unknown command "secrets" for "stripe apps".`

**Expected behavior**
Expect to receive an API response with Secret Store data matching the documented behavior.

**Screenshots**
<img width="653" alt="image" src="https://github.com/stripe/stripe-apps/assets/2487968/3f48e9a7-25a5-4348-bd2d-cc59c079b4d1">

**Desktop (please complete the following information):**
 - OS: macOS 14.21.1
 - Stripe CLI Version 1.19.2
 - Stripe Apps CLI Plugin Version v1.5.15

**Additional context**
Stripe CLI was installed on macOS using homebrew. No other unusual behavior has been observed while using the Stripe CLI and the Apps plugin.

**Comment by gabrielhurley-stripe** [comment]
That was added to the docs erroneously. The command does not actually exist! We'll remove it from the docs.

The information in https://docs.stripe.com/stripe-apps/store-secrets are the correct examples of how to interact with Secret Store.

If there's a use case you'd like to see supported in the CLI, we'd be interested in understanding the feature request.

Thanks!

**Comment by tvanantwerp** [comment]
@gabrielhurley-stripe My use case was customer support for a Stripe App. We were storing some configuration settings in a secret, and I wanted to check if these configuration settings might have errors in them that were causing an issue for them. Using the Stripe CLI would've been an easy way to fetch that secret to view the settings. I didn't particularly like using a production API key on the app account to locally request the connected account's secret via API endpoint. Having a way to do this via the CLI would be quicker, and more secure since I wouldn't need that API key.
