### ISSUE TITLE
Installation failed: parameter_invalid_empty - channel_link_id

### ISSUE THREAD

**Issue by obrunsmann** [stripe/stripe-apps#953]
**Describe the bug**
Without any changes to our integration, the installations suddenly fail:

request
```JSON
{
  "app_id": "tailorapp*xxx",
  "channel_id": "appchannel*xxx",
  "mode": "LIVEMODE",
  "channel": "PUBLIC",
  "merchant_id": "acct_xxx",
  "channel_link_id": ""
}
```

Request ID req_PBqoJw9ImhsqvM

response
```json
{
  "error": {
    "code": "parameter_invalid_empty",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-invalid-empty",
    "message": "You passed an empty string for 'channel_link_id'. We assume empty values are an attempt to unset a parameter; however 'channel_link_id' cannot be unset. You should remove 'channel_link_id' from your request or supply a non-empty value.",
    "message_code": "invalid_empty_parameter",
    "param": "channel_link_id",
    "request_log_url": "https://dashboard.stripe.com/test/logs/req_PBqoJw9ImhsqvM?t=1709624517",
    "type": "invalid_request_error"
  }
}
```

<img width="1633" alt="image" src="https://github.com/stripe/stripe-apps/assets/763812/71dd545e-f2dd-4485-929b-71b7815118d5">

Even if I copy the redirect URL from the app settings, the installation no longer works.

The problem is very urgent as all our new users are affected.

**To Reproduce**
1. Copy redirect URL
2. Open and confirm installation
3.  → error

**Expected behavior**
Successful installation

**Screenshots**
<img width="1629" alt="image" src="https://github.com/stripe/stripe-apps/assets/763812/9575a862-b2a4-4fcc-a91b-edb1d2ea7988">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version latest

**Comment by ngrubb-stripe** [comment]
@obrunsmann - thanks for reporting this! We just pushed out a fix for this issue, OAuth app installations should be working for you again.

**Comment by obrunsmann** [comment]
> @obrunsmann - thanks for reporting this! We just pushed out a fix for this issue, OAuth app installations should be working for you again. 

Thank you. It's working again!
