### ISSUE TITLE
Not able to release App in Live Mode

### ISSUE THREAD

**Issue by LZ-KB3D** [stripe/stripe-apps#967]
**Describe the bug**
I have a private distribution App, when I create a new version I can see the new version here: https://dashboard.stripe.com/apps/[AppName] but when I try to deploy this new version to Live Mode I get "App already installed" message and I am unable to release the new version

**To Reproduce**
1. Go to https://dashboard.stripe.com/apps/[AppName] 
2. Create a release (top right)
3. Choose version 0.0.61 (currently installed is 0.0.57)
4. Install app menu pops up
5. Click on Install App
6. Install [AppName] on [OrganizationName] pops up
7. Click on continue
8. "App already installed" message shows up

**Expected behavior**
I expect the new version to be installed in Live Mode

**Screenshots**
Current state:
![image](https://github.com/stripe/stripe-apps/assets/159828138/f35669c0-4150-4f73-8ec1-a2a530ddd3c3)
Settings:
![image](https://github.com/stripe/stripe-apps/assets/159828138/dbffb147-b1ea-401d-a7f8-7e6486d6601d)
Result:
![image](https://github.com/stripe/stripe-apps/assets/159828138/645c4a6e-6062-41cb-9ea7-da1e590fde85)

**Desktop (please complete the following information):**
 - OS: tried on iOS and Windows (I don't believe this matters)
 - Browser Chrome
 - Version 124.0.6367.119 

**Additional context**
Just the fact that this is a privately distributed app, I only want it available for my team members I am NOT trying to release for the app marketplace

**Comment by LZ-KB3D** [comment]
@ngrubb-stripe this seems to have been fixed btw

**Comment by ngrubb-stripe** [comment]
> @ngrubb-stripe this seems to have been fixed btw

Thanks, apologies that I didn't leave an update! This is fixed.
