### ISSUE TITLE
Stripe report_runs don't return success for a long time

### ISSUE THREAD

**Issue by NoamKashtan** [stripe/stripe-apps#969]
**Describe the bug**
I'm using the "https://api.stripe.com/v1/reporting/report_runs" for a while. A pending status has suddenly been given to me for a very long time. 

**To Reproduce**
1. using this URL (get): https://api.stripe.com/v1/reporting/report_runs/frr_1PJ83XCU1g4y0fcoLwWDNM33
2. response is: 
{
    "id": "frr_1PJ83XCU1g4y0fcoLwWDNM33",
    "object": "reporting.report_run",
    "created": 1716356983,
    "error": null,
    "livemode": true,
    "parameters": {
        "columns": [
            "id",
            "type",
            "currency",
            "transaction_date_utc",
            "transaction_date",
            "tax_date_utc",
            "tax_date",
            "refund_id",
            "line_item_id",
            "subtotal",
            "total",
            "tax_behavior",
            "tax_code",
            "jurisdiction_name",
            "jurisdiction_level",
            "country_code",
            "state_code",
            "taxability",
            "taxability_reason",
            "tax_rate",
            "tax_name",
            "tax_type",
            "quantity",
            "payment_intent_id",
            "customer_tax_id",
            "origin_resolved_address_line1",
            "origin_resolved_address_line2",
            "origin_resolved_address_city",
            "origin_resolved_address_state",
            "origin_resolved_address_postal_code",
            "origin_resolved_address_country",
            "destination_resolved_address_line1",
            "destination_resolved_address_line2",
            "destination_resolved_address_city",
            "destination_resolved_address_state",
            "destination_resolved_address_postal_code",
            "destination_resolved_address_country",
            "taxable_amount",
            "non_taxable_amount",
            "tax_amount",
            "filing_currency",
            "filing_exchange_rate",
            "filing_total",
            "filing_non_taxable_amount",
            "filing_taxable_amount",
            "filing_tax_amount"
        ],
        "interval_end": 1716076800,
        "interval_start": 1715472001
    },
    "report_type": "tax.transactions.itemized.1",
    "result": null,
    "status": "pending",
    "succeeded_at": null
}

**Expected behavior**
It should be in status "succeeded" after a 1-3 minutes usually. 

I'm not sure if something has been change here in the request behaviour.
Thanks.

**Comment by jsteele-stripe** [comment]
This repo is specifically for issues relating to [Stripe Apps](https://docs.stripe.com/stripe-apps). For technical support with other Stripe products or API, you should reach out to [support](https://support.stripe.com/?contact=true) directly.

**Comment by NoamKashtan** [comment]
Thanks
