### ISSUE TITLE
External test install links exit the flow when selecting any account other than the current

### ISSUE THREAD

**Issue by efouts** [stripe/stripe-apps#974]
**Describe the bug**
When using an install link as part of an external test if I choose any Stripe account other than the first (current selected), i'm immediately redirected to the dashboard with the selected account selected. 

**To Reproduce**
1. Create an external test using an install link with a redirect uri
2. Navigate to the provided install link
3. Select any account other than the first in the list
4. Notice the flow is abandoned and you're redirected to the dashboard for the selected account

**Expected behavior**
I expect the flow to proceed with installing the app regardless of which account is selected. 

**Screenshots**
Selecting any Stripe account other than the first in the list in the provided screenshot will reproduce the issue. 
<img width="1141" alt="Screenshot 2024-06-18 at 7 33 28 PM" src="https://github.com/stripe/stripe-apps/assets/1428145/d6376fcd-2ec6-45c7-bb9d-bb35d778b363">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.5
 - Browser: Chrome
 - Version: 126.0.6478.61

**Additional context**
I can provide an install link if needed.

**Comment by chaves-stripe** [comment]
This is resolved!
