### ISSUE TITLE
"App directory links" page is shown to the viewer instead of our app

### ISSUE THREAD

**Issue by bensontrent** [stripe/stripe-apps#977]
I have a public and published app available in the Apps Marketplace.  But, yesterday, our `stripe.dashboard.drawer.default` viewport began showing the soft error screen.   Was there a recent update in the Stripe Apps codebase that could be causing this error?

Our most recent publish was approved and pushed to the public on Monday, but something in the Stripe Apps platform changed that causes our default view to show the "Soft Error" page "Choose a page below to get started with Parcelcraft Shipping:"

![image](https://github.com/stripe/stripe-apps/assets/5982592/14e12066-8a93-4f91-b289-c559af5abfbe)

We're trying to workshop this bug, but we do not see any error messages in the console, and no errors when running `stripe apps start --log-level=debug`, 

In the weeks leading up to the "Soft fail" error, we noticed the fallback app directory would flash on the screen for a few milliseconds while our app was loading.  

I'm unable to recreate this error using a Stripe example app, so I'm led to believe there's some misconfiguration in our app.  But we don't know what kind of misconfiguration would lead to the app presenting the failure screen, or what conditions Stripe Platforms looks for before presenting the "Soft fail" screen

 I've confirmed it's not an issue with our codebase; in a local test, I replaced our `App.tsx` with the simplest component possible. 
We're seeing the same issue when we preview the app with essentially no code.

```
import type { ExtensionContextValue } from '@stripe/ui-extension-sdk/context';
import { Box, ContextView } from '@stripe/ui-extension-sdk/ui';
import { useEffect } from 'react';

const App = ({ userContext, environment, appContext }: ExtensionContextValue) => {

  const context = {
    userContext,
    environment,
    appContext
  };

  useEffect(() => {
    console.log(context);

  }, [])

  return (

    <ContextView title="Test">
      <Box>Test</Box>
    </ContextView>
 
  )
}

export default App
````

However, we do see the console.log message in our test component, so the component is loaded, and then it errors out to the fallback-app directory view.  That leads me to believe there's some issue with our stripe-app.json or package.json in the new Stripe Apps Platform environment, but I'm wondering if you've run into this issue before or have any tips.

**Comment by bensontrent** [comment]
I can confirm this is an issue with the Stripe Apps platform: rolling back to an older version of our app before this issue became a problem is now a problem at dashboard.stripe.com .  Something in the Stripe black-box code was changed to induce this issue.

You can view this issue by installing our app from https://marketplace.stripe.com/apps/parcelcraft-shipping

**Comment by bensontrent** [comment]
Here's some more context for this error:

- Other pages within our app work as expected.  Only the "stripe.dashboard.drawer.default" is affected. This is unusual since our InvoiceDetailView, PaymentDetailView, and CustomerDetailView present are nearly identical: they share most routes and backend server.
- I investigated if this was related to my package.json (NPM reported a critical security update--I ran `npm audit fix` and still the problem persists).  I also tried duplicating the versions in the Stripe Routing App Example. (This example does not present a problem when run locally)
- I ruled out compile issues and app issues by installing a previous version for Test Mode from the Stripe Dashboard-- Previous versions had no problems, but now they do.

**Comment by gabrielhurley-stripe** [comment]
Thanks for the thorough investigation. We'll check it out ASAP and figure out what's going on.

**Comment by tennhard-stripe** [comment]
Thank you for bringing this issue to our attention and for the detailed investigation you've done to isolate the problem. We really appreciate you taking the time to provide such comprehensive information - it was very helpful as we looked into this.

I'm glad to report that we have now resolved the issue you were experiencing. The problem was indeed on our end, and we have made the necessary changes to restore proper functionality.

Please feel free to reopen the issue should you have any other questions or concerns. We're here to support you and ensure your app continues to perform as expected.

**Comment by bensontrent** [comment]
Awesome! Thank you for recognizing this as a critical bug and fixing it so quickly. I very much appreciate it.  I'll email our customers to let them know the issue has been resolved.
