### ISSUE TITLE
External api request is blocked by cors

### ISSUE THREAD

**Issue by TilWiggers** [stripe/stripe-apps#981]
**Describe the bug**
I want to fetch data from an external api from a "Stripe Apps frontend component". But I get the error: "Content-Security-Policy: The page’s settings blocked the loading of a resource at https://google.com/ (“connect-src”)." 

**To Reproduce**
1. Specify the url in the manifest:
```json
    "content_security_policy": {
      "connect-src": [
        "https://google.com"
      ],
      "image-src": null,
      "purpose": "test"
    }
``` 
2. Invoke fetch
```ts
fetch("https://google.com", {
    body,
    method: "GET",
    headers: {
        "Authorization": this.token,
        "Content-Type": "application/x-www-form-urlencoded"
    }
})
```

**Expected behavior**
I expect the request not to be blocked by CORS.

**Screenshots**
![image](https://github.com/user-attachments/assets/1fa53016-3263-4b6d-9b41-a9e59a82c0ea)

**Desktop:**
 - OS: Linux
 - Browser Firefox

**Additional context**
I double checked by using the "isSourceInAuthorizedCSP" function to confirm that the url is authorized.
```ts
console.log("isSourceInAuthorizedCSP", await isSourceInAuthorizedCSP(`https://google.com`), `https://google.com`);
```

https://google.com is used as a placeholder for the actual api endpoint. The actual api states:
> This API features Cross-Origin Resource Sharing (CORS).
It enables cross-domain communication from the browser.
All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.

**Comment by bensontrent** [comment]
You'll need to proxy your request to google to handle cors.  For example in a Express app, you can add the necessary coors headers.  See https://docs.stripe.com/stripe-apps/build-backend#handle-cross-origin-resource-sharing-(cors)

```js
import cors from "cors";
import express from "express";
import { createProxyMiddleware } from 'http-proxy-middleware';
const app = express();

app.use(cors());



const GoogletProxy = createProxyMiddleware({
  target: 'https://www.google.com', // target host with the same base path
  changeOrigin: true,
  autoRewrite:true,
  logLevel: 'debug',
  pathRewrite: {
    [`^/api/google`]: '',
},
});
app.use('/api/google', GoogletProxy );
````

**Comment by TilWiggers** [comment]
The proxy did the trick. Thanks!
