### ISSUE TITLE
Tooltips have incorrect z-index; Tooltip content appears behind app layer

### ISSUE THREAD

**Issue by bensontrent** [stripe/stripe-apps#982]
This is a new issue that has appeared in at least the last 48 hours.  The tooltip component is not functioning properly.   Tooltips appear behind the app instead of as a pop-up relative to the pop-up element's trigger.

See the screenshot for reference.

![image](https://github.com/user-attachments/assets/f5374eb9-ac9c-4386-b585-1e6ba3bb108f)

**Comment by aaronhernandez-stripe** [comment]
Thanks for bringing this to our attention, @bensontrent.
A solution to the underlying issue has been identified and we're preparing to deploy a fix shortly.

**Comment by aaronhernandez-stripe** [comment]
The fix has been successfully deployed, thank you again for your patience.
Please feel free to reach out if you have any further issues or concerns.
