### ISSUE TITLE
When opening the Settings view from the app, inappropriate margins are applied

### ISSUE THREAD

**Issue by bensontrent** [stripe/stripe-apps#984]
When opening the settings view from the app, the view does not expand to all available real estate in the browser.   We depend on this real estate to properly show the available columns with appropriate spacing on a 1024-pixel-wide screen.  This is a new behavior that has appeared in the last few months.

![parcelcraft-bulk-printing](https://github.com/user-attachments/assets/3a8cc224-f462-4eb1-932b-580e0c14a052)

This is the default view when opening settings from the app:

![image](https://github.com/user-attachments/assets/ee755460-68cb-4d2d-a687-f4ec439e2c73)

A browser-refresh of the settings view (see our app at https://dashboard.stripe.com/settings/apps/com.productivity.parcelcraft after installing from https://marketplace.stripe.com/apps/parcelcraft-shipping)  will show the appropriate spacing:

![image](https://github.com/user-attachments/assets/29e037f3-1128-4a64-b69f-8583dc4921e4)

**Comment by aaronhernandez-stripe** [comment]
Thank you, @bensontrent, for bringing this to our attention. We’ve fixed the issue and deployed it, so everything should be working fine now.
Please feel free to reach out if you have any further issues or concerns.
