### ISSUE TITLE
Banner component in 9.0.0-alpha.15 has incorrect css for inline action items.

### ISSUE THREAD

**Issue by bensontrent** [stripe/stripe-apps#994]
The screenshots below show an issue with the version 9 beta of the SDK.  Inline elments of the `action` attribute are not afforded appropriate space, and (minor issue) links do not have the appropriate color.

Banner component in [9.0.0-alpha.15](https://www.npmjs.com/package/@stripe/ui-extension-sdk/v/9.0.0-alpha.15)

![image](https://github.com/user-attachments/assets/f5426e07-04ce-4ab8-9e4a-70a91542f4d3)

Banner component in [8.9.1](https://www.npmjs.com/package/@stripe/ui-extension-sdk/v/8.9.1):

![image](https://github.com/user-attachments/assets/de0ce173-b2e9-4ee0-9ae5-eada1868e2fc)

Code sample:

```tsx
<Banner
  type="critical"
  title="Invalid API Key"
  description="You must enter a PRODUCTION API Key from EasyPost.  You'll still be able to print test labels in Parcelcraft with a Production API Key."
  actions={ <Link href="https://www.easypost.com/signup?utm_source=Parcelcraft" target="_blank" external>Get my free API Key</Link> }
 />
```

**Comment by matebek-stripe** [comment]
Thanks for reporting @bensontrent! A fix has been rolled out for the Banner action prop width. The color of the link is intended to match the Banner in version 9.
